### ISSUE TITLE
[Feature] Power profiles

### ISSUE THREAD

**Issue by Vixea** [ilya-zlobintsev/LACT#109]
Support setting power profiles main motivator for this issue is this Steamvr issue here: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/469

**Comment by ilya-zlobintsev** [comment]
This should be possible to implement, I will take a look at it.

**Comment by ilya-zlobintsev** [comment]
This is now implemented (albeit in a limited form, you can't view detailed information about the presets), please try running the latest git version and tell me if it works for you.

**Comment by Vixea** [comment]
It works for me!
