### ISSUE TITLE
Fan Speed indicator not working

### ISSUE THREAD

**Issue by Alexander-LIT** [ilya-zlobintsev/LACT#12]
After my comment on Reddit the 6900XT Red 'Devil is now correctly identified. Thank you!

Another issue that I found is that while the slider to control the fans do seem to work perfectly, the reported Fan Speed is always 0 RPM and 0%. I am not sure if this is an issue with the application or whether the feature is not fully supported in the kernel yet? It "sort of" works in CoreCtl where it will sometimes show fanspeed, and no fanspeed at others.

I am on Manjaro with Kernel 5.11.1-1 with Mesa 20.3.4-3 if that helps.

Edit: Additional feedback would be that it might be nice to be able to see the current temperture and perhaps fan speed in the OC tab. Generally, if I am overclocking something, I also monitor the temperature. This would remove the need to switch back and forth between tabs. Maybe renaming the "Thermals" tab to something like "Fancontrol" would make sense in that case.

Cheers!

Full blast fans at 0% 
![2021-03-02_13-06](https://user-images.githubusercontent.com/63505691/109646242-3dda7e80-7b58-11eb-9f71-22dfc178bfae.png)

**Comment by ilyazzz** [comment]
What's the output of 
`cat /sys/class/drm/card0/device/hwmon/*/fan*_input` 
when this happens?

Most likely it's a bug in the kernel's reporting (on my RX 580 it keeps showing the last non-zero value when the fans turn off, so it wouldn't be surprising if there are other issues with it, especially on very new GPUs). Though if the fan speed is actually correctly set, that means that the driver properly reports minimum and maximum values for the speeds.

BTW, How does the overclocking work? I've implemented it according to the driver documentation, but as I don't have a new GPU to test it on please report if there are any issues. (also there's no voltage control currently)

**Comment by ilyazzz** [comment]
I've added GPU temperature and usage indicators to the OC page.

**Comment by Alexander-LIT** [comment]
Thank you for your replies ilyazzz!

Output of:
```
cat /sys/class/drm/card0/device/hwmon/*/fan*_input
0
```

When I try the OC settings the following happens:
Automatic: Card uses a variety of clockspeeds between 0 - 500 - 2565
Highest Clocks: Card switches between 0 and 2565 (with slight fluctuation in the maxclock 2555-2565)
Lowest Clocks: Card switches between 0 and 500Mhz

My card is still set to "Quiet" BIOS since I am still lacking a waterblock for it.
I read that full overclocking support was not going to be available until kernel 5.12 I believe?

**Comment by ilyazzz** [comment]
The kernel does seem to be reporting 0 as the fan speed. It would be possible to show the fan speed values that the daemon tells the driver to use, but that's less accurate than reading the actual RPM values of the fan.

As for overclocking, I'm curious on how it works on all GPUs that use the new format, which are Vega20(Radeon VII/Navi) and newer. If the clockspeed sliders don't show up even after the kernel parameter, then most likely the kernel doesn't support overclocking on your GPU yet.

**Comment by Alexander-LIT** [comment]
I will report back in when 5.12 releases on Manjaro.
If there is any more information I can supply that would be useful, please let me know :-)

**Comment by ilya-zlobintsev** [comment]
Closing because of age and most likely being a problem on the kernel side, please re-open if you still have the issue.
