### ISSUE TITLE
I can't apply my configuration

### ISSUE THREAD

**Issue by TeaHistoria** [ilya-zlobintsev/LACT#149]
![Screenshot from 2023-04-03 23-32-30](https://user-images.githubusercontent.com/129779202/229572556-d6658aea-fc14-40fd-844b-f38eb576b553.png)

Like this image

**Comment by TeaHistoria** [comment]
Here my ROG Advantage Specs with RX 6800M

OS: Arch Linux x86_64 
Host: ROG Strix G513QY_G513QY 1.0 
Kernel: 6.2.8-zen1-1-zen 
Uptime: 1 hour, 21 mins 
Packages: 1563 (pacman), 6 (flatpak) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
DE: GNOME 43.3 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Numix-Circle [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 3.300GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT
Memory: 5803MiB / 15391MiB

**Comment by TeaHistoria** [comment]
Maybe something is wrong with my configuration but I've tried on and off kernel parameters and nothing happened.

/etc/modprobe.d/amdgpu.conf

blacklist radeon
options radeon si_support=0
options radeon cik_support=0
options amdgpu si_support=1
options amdgpu cik_support=1
options amdgpu ppfeaturemask=0xffffffff


/etc/default/grub

GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 amdgpu.ppfeaturemask=0xffffffff"

**Comment by ilya-zlobintsev** [comment]
Did you enable and start the daemon? You can check it with `systemctl status lactd`
LACT gives you a warning on startup about not being able to change settings if you don't have the daemon running.

**Comment by TeaHistoria** [comment]
yeah i enable it

lactd.service - AMDGPU Control Daemon
     Loaded: loaded (/usr/lib/systemd/system/lactd.service; enabled; preset: disabled)
     Active: active (running) since Tue 2023-04-04 20:32:32 WIB; 6h left
   Main PID: 829 (lact)
      Tasks: 3 (limit: 18423)
     Memory: 12.5M
        CPU: 60ms
     CGroup: /system.slice/lactd.service
             └─829 lact daemon

Apr 04 20:32:32 anarki systemd[1]: Started AMDGPU Control Daemon.
Apr 04 20:32:32 anarki lact[829]: 2023-04-04T13:32:32.090574Z  INFO lact_daemon::socket: listening on "/var/run/lactd.sock"

**Comment by TeaHistoria** [comment]
maybe there really was an error in my arch linux installation, when i ran the command

cat /sys/class/drm/card1/device/pp_sclk_od
0

the output is "0" instead

I just realized 6 hours ago. maybe I'll reinstall the OS again when I have free time and try the LACT program and report the results in this comment

**Comment by ilya-zlobintsev** [comment]
Could you set `log_level` to `debug` in `/etc/lact/config.yaml`, then try applying settings again and check the logs in
```
sudo journalctl -u lactd -e | grep PowerCap
```
Looks like laptop GPUs don't allow editing some settings that LACT tries to apply

**Comment by ilya-zlobintsev** [comment]
> maybe there really was an error in my arch linux installation, when i ran the command
> 
> cat /sys/class/drm/card1/device/pp_sclk_od 0
> 
> the output is "0" instead
> 
> I just realized 6 hours ago. maybe I'll reinstall the OS again when I have free time and try the LACT program and report the results in this comment

This file is not used by LACT, it's normal for it to output `0`. It's unlikely to be a problem with your installation, and more to do with specific gpu type quirks (laptop GPU in your example, which LACT was not heavily tested with)

**Comment by TeaHistoria** [comment]
but from the first time I bought this laptop 2 years ago, I had a problem with the vram mclk stuck at 1000mhz and never found a solution

**Comment by TeaHistoria** [comment]
> This file is not used by LACT, it's normal for it to output `0`. It's unlikely to be a problem with your installation, and more to do with specific gpu type quirks (laptop GPU in your example, which LACT was not heavily tested with)

people who run this command get the result like below

sudo cat /sys/class/drm/card0/device/pp_od_clk_voltage

OD_SCLK:
0:        300MHz        750mV
1:        588MHz        765mV
2:        980MHz        987mV
3:       1100MHz        950mV
4:       1100MHz        950mV
5:       1100MHz        950mV
6:       1100MHz        950mV
7:       1100MHz        950mV
OD_MCLK:
0:        300MHz        750mV
1:       1000MHz        800mV
2:       1970MHz        950mV
OD_RANGE:
SCLK:     300MHz       2000MHz
MCLK:     300MHz       2250MHz
VDDC:     750mV        1150mV



But the results I get are blank

**Comment by TeaHistoria** [comment]
[tea@anarki | ~]
==> cat /sys/class/drm/card0/device/pp_dpm_mclk
0: 96Mhz *
1: 456Mhz 
2: 675Mhz 
3: 1000Mhz 
[tea@anarki | ~]
==> sudo cat /sys/class/drm/card0/device/pp_od_clk_voltage
[sudo] password for tea: 

[tea@anarki | ~]
==> cat /sys/class/drm/card0/device/pp_od_clk_voltage

[tea@anarki | ~]
==> cat /sys/class/drm/card1/device/pp_od_clk_voltage

[tea@anarki | ~]
==> cat /sys/class/drm/card0/device/pp_dpm_mclk
0: 96Mhz *
1: 456Mhz 
2: 675Mhz 
3: 1000Mhz 
[tea@anarki | ~]
==> cat /sys/class/drm/card1/device/pp_dpm_mclk
0: 1600Mhz 
1: 400Mhz *
[tea@anarki | ~]

**Comment by ilya-zlobintsev** [comment]
> But the results I get are blank

This is expected on integrated and laptop GPUs, and is not the reason you can't apply settings. The error comes from not being able to set the power limit (which may not be configurable on a laptop)

**Comment by TeaHistoria** [comment]
![Screenshot from 2023-04-04 14-20-51](https://user-images.githubusercontent.com/129779202/229717867-267008da-2fcc-4fa2-b563-cd158a4482dc.png)

maybe, this is because the newly introduced sPPT settings don't have the right driver, so what I'm looking for on the Internet are very few posts with the keyword "Linux sPPT"

Indeed, this is a bit strange where the CPU and GPU power consumption are combined into the sPPT Platform. When I set the CPU limit to be greater than the GPU (APU sPPT), the power is focused on the CPU, so the power on the GPU is left over from the limit.

APU sPPT = 60W
Platforms sPPT = 100W

if programs/games that require a lot of CPU are usually like this
Platforms sPPT (Total power) = 100W
CPU = 60W
GPUs = 40W

actually for what AMD to make laptop settings like this?

**Comment by ilya-zlobintsev** [comment]
LACT will now avoid setting the power limit unless it was changed by the user, this will not make the setting available on your system, but it should make it possible to change other settings.
