### ISSUE TITLE
Icon suggestions

### ISSUE THREAD

**Issue by ilya-zlobintsev** [ilya-zlobintsev/LACT#15]
It would be nice for LACT to have an icon. If anyone wants to make one or finds one with a license that allows it's usage, suggest it here.

**Comment by Llorrin** [comment]
i created this if you like that
![lact](https://user-images.githubusercontent.com/42930870/110041815-0aa91280-7d45-11eb-97aa-6726e643a57c.jpg)

**Comment by Llorrin** [comment]
and also this
![lact2](https://user-images.githubusercontent.com/42930870/110111166-30b7cc80-7db0-11eb-9a3a-b2939da77735.png)

**Comment by ilyazzz** [comment]
Thanks for these suggestions, but I would prefer something that's without text, but you can still recognize that the program is for hardware settings. Maybe a drawn PCB?

**Comment by Llorrin** [comment]
something like this?

![lact8](https://user-images.githubusercontent.com/42930870/110174524-8916ba80-7e00-11eb-8622-a8b8fd8aa456.png)

**Comment by ilyazzz** [comment]
@Llorrin if you don't mind, I've made a slightly different version based on your one:
![pic](https://i.imgur.com/GUl5yJq.png)

The black outline will probably have to be changed in order to be used in dark themes.

**Comment by Llorrin** [comment]
@ilyazzz  ok  i didnt have enough time yesterday to imporve it, i have the file on Krita though i can make changes there.

can you check my question i pm you on reddit?

**Comment by Llorrin** [comment]
here 
![lact-darktheme](https://user-images.githubusercontent.com/42930870/110200201-05d78200-7e5d-11eb-86f9-1efe31292a79.png)


it looks like this on my desktop

![lact test](https://user-images.githubusercontent.com/42930870/110200218-17b92500-7e5d-11eb-9575-e14cf3e9dd5f.png)

**Comment by Llorrin** [comment]
i have also created this that matches my mac themed kde desktop

![lact AMDGPU-black](https://user-images.githubusercontent.com/42930870/110200503-aa0df880-7e5e-11eb-9f26-b7225b9a806c.png)

**Comment by Big-FG** [comment]
This is a sketch i did for a logo, its a bit rough but gets the idea

![lact](https://user-images.githubusercontent.com/81116028/133651008-66836473-0f09-4cc8-aec8-c25ae2025220.png)

**Comment by ilya-zlobintsev** [comment]
> i have also created this that matches my mac themed kde desktop
> 
> ![lact AMDGPU-fuzzy](https://user-images.githubusercontent.com/42930870/110210037-09d0c780-7e90-11eb-9641-0907b653fbc5.png) ![lact test](https://user-images.githubusercontent.com/42930870/110210043-12290280-7e90-11eb-9ee3-77adf16c1c6a.png)

@NalianNalis sorry for the very long delay, but the latest release now uses your icon! https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.2.0
