### ISSUE TITLE
It won't read my gpu

### ISSUE THREAD

**Issue by Faugus** [ilya-zlobintsev/LACT#159]
AMD Radeon 6800XT
Installed through AUR and enabled/started the service.

![image](https://user-images.githubusercontent.com/112667550/232862305-fd22cb0b-3edb-4202-8a75-461edc41bec2.png)

`2023-04-18T17:50:10.586476Z ERROR lact_gui::app: Could not fetch stats: Got error from daemon: No controller with such id
2023-04-18T17:50:10.837018Z ERROR lact_gui::app: Could not fetch stats: Got error from daemon: No controller with such id
2023-04-18T17:50:11.087490Z ERROR lact_gui::app: Could not fetch stats: Got error from daemon: No controller with such id
2023-04-18T17:50:11.338026Z ERROR lact_gui::app: Could not fetch stats: Got error from daemon: No controller with such id
`

**Comment by ilya-zlobintsev** [comment]
Could you check the service logs in `sudo journalctl -u lactd -e`? Also, what is the output of the following command: 
```
echo '{"command": "list_devices"}' | ncat -U /run/lactd.sock
```

**Comment by Faugus** [comment]
`Apr 18 14:58:23 archlinux systemd[1]: Started AMDGPU Control Daemon.
Apr 18 14:58:23 archlinux lact[388]: 2023-04-18T17:58:23.769809Z  INFO lact_daemon::socket: listening on "/var/run/lactd.sock"
`

`[faugus@archlinux ~]$ sudo echo '{"command": "list_devices"}' | ncat -U /run/lactd.sock
bash: ncat: command not found`

**Comment by ilya-zlobintsev** [comment]
Try installing `nmap` and running the command again.
Additionally, what does `cat /sys/class/drm/card*/device/uevent` return?

**Comment by Faugus** [comment]
```
[faugus@archlinux ~]$ echo '{"command": "list_devices"}' | ncat -U /run/lactd.sock
{"status":"ok","data":[]}
```
```
faugus@archlinux ~]$ cat /sys/class/drm/card*/device/uevent
DRIVER=amdgpu
PCI_CLASS=30000
PCI_ID=1002:73BF
PCI_SUBSYS_ID=1043:04F2
PCI_SLOT_NAME=0000:09:00.0
MODALIAS=pci:v00001002d000073BFsv00001043sd000004F2bc03sc00i00
MAJOR=226
MINOR=0
DEVNAME=dri/card0
DEVTYPE=drm_minor
MAJOR=226
MINOR=0
DEVNAME=dri/card0
DEVTYPE=drm_minor
MAJOR=226
MINOR=0
DEVNAME=dri/card0
DEVTYPE=drm_minor
MAJOR=226
MINOR=0
DEVNAME=dri/card0
DEVTYPE=drm_minor
```

**Comment by ilya-zlobintsev** [comment]
Could you also show the output of `ls /sys/class/drm/card*`?

**Comment by ilya-zlobintsev** [comment]
@Faugus I've pushed an update to the GPU detection logic, please try with the `lact-git` package and tell me if it fixes the problem

**Comment by Faugus** [comment]
```
[faugus@archlinux ~]$ ls /sys/class/drm/card*
/sys/class/drm/card0:
card0-DP-1  card0-DP-2  card0-DP-3  card0-HDMI-A-1  dev  device  power  subsystem  uevent

/sys/class/drm/card0-DP-1:
ddc  device  dpms  drm_dp_aux0  edid  enabled  i2c-10  modes  power  status  subsystem  uevent

/sys/class/drm/card0-DP-2:
ddc  device  dpms  drm_dp_aux1  edid  enabled  i2c-11  modes  power  status  subsystem  uevent

/sys/class/drm/card0-DP-3:
ddc  device  dpms  drm_dp_aux2  edid  enabled  i2c-12  modes  power  status  subsystem  uevent

/sys/class/drm/card0-HDMI-A-1:
ddc  device  dpms  edid  enabled  modes  power  status  subsystem  uevent

```

```
requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
error: could not set install reason for package rust (could not find or read package)
 -> error installing repo packages
error installing repo packages
[faugus@archlinux ~]$ 
```

**Comment by Faugus** [comment]
A suggestion: swap the positions of Minimum VRAM Clock with Maximum GPU clock to be easier do see and control, like:

Minimum GPU Clock (MHz)
Maximum GPU Clock (MHz)
Minimum VRAM Clock (MHz)
Maximum VRAM Clock (MHz)

![image](https://user-images.githubusercontent.com/112667550/234025498-5ebb64c3-639c-4075-b16c-ea6672204f9e.png)

**Comment by Faugus** [comment]
I restarted my PC and now it won't recognize my GPU anymore.
Corectrl is working fine.

Another suggestion: add an option to set a fixed fan speed.

**Comment by ilya-zlobintsev** [comment]
@Faugus could you try restarting the daemon (`sudo systemctl restart lactd`) and see if the GPU is detected then? The issue appearing after a reboot makes me think it could be related to the service starting too early, before the sysfs is initialized. CoreCtrl is a graphical application which gets started much later, so it wouldn't have this problem.

**Comment by Faugus** [comment]
Restarting the service worked.

**Comment by Faugus** [comment]
I tried to set the minimum VRAM clock and the screen just got full of artifacts, even setting the mem clock to 1000 (the default).
I hard reset the PC and now when I restart the lactd service, the screen gets those artifacts because the software saved that OC.

**Comment by ilya-zlobintsev** [comment]
> I tried to set the minimum VRAM clock and the screen just got full of artifacts

Unfortunately this is just how some GPUs react to setting the clockspeed. There is a settings confirmation feature in the works that would help prevent you from getting into such a situation and saving the faulty settings, though there is no way to detect every possible situation when the GPU can misbehave. In the meanwhile, you can manually edit `/etc/lact/config.yaml` and remove the minimum memory clock.

I will however look into retrying the GPUs query to avoid the race condition at boot.

**Comment by ilya-zlobintsev** [comment]
LACT will now attempt to retry loading GPUs if it didn't find any, this should make the GPU pick up reliably after a reboot.

**Comment by ilya-zlobintsev** [comment]
I'm closing this issue as it should be fixed now, if you have it again please reopen it.
