### ISSUE TITLE
No Fan Control on RX7900 Series

### ISSUE THREAD

**Issue by PorcelainMouse** [ilya-zlobintsev/LACT#187]
I've been looking everywhere for this ability, but I can't find it in any tool; I've tried three. I'm assuming you're all having the same issues, but maybe it's me?  Do you know that LACT should work on this card?  Because I can't get it to work.

**Comment by ilya-zlobintsev** [comment]
If it doesn't show up in any of the tools, then most likely it's not exposed by the driver. Could you post the output of
```
ls /sys/class/drm/card*/device/hwmon/hwmon*/
```

**Comment by PorcelainMouse** [comment]
```
$ ls /sys/class/drm/card1/device/hwmon/hwmon3/
device@      freq1_label  power1_average      pwm1_enable      temp1_input      temp3_crit
fan1_enable  freq2_input  power1_cap          pwm1_max         temp1_label      temp3_crit_hyst
fan1_input   freq2_label  power1_cap_default  pwm1_min         temp2_crit       temp3_emergency
fan1_max     in0_input    power1_cap_max      subsystem@       temp2_crit_hyst  temp3_input
fan1_min     in0_label    power1_cap_min      temp1_crit       temp2_emergency  temp3_label
fan1_target  name         power1_label        temp1_crit_hyst  temp2_input      uevent
freq1_input  power/       pwm1                temp1_emergency  temp2_label
```

The sys interface looks exactly like it does for all the other cards; all the files are there. And, that worked on my previous two AMD cards with the software I have.  I've even checked my 6800xt on this driver, which works.  It's just that nothing you do to them has any effect. If you write '1' to pwm1_enable, there's no error, but it doesn't change it's value.  I agree, it seems like there is a problem with the driver, but then you'd be seeing this for all cards on AMDGPU.  Maybe -PRO works, but I can't try that.  Well, maybe I should work on that, but I can't do it currently.

I think it's really strange that the driver doesn't support this card like last gen's cards, but it very clearly did not, at least at one point: https://gitlab.freedesktop.org/drm/amd/-/issues/2402 . It looks to me like it is still not supported, but I'm hoping beyond hope that one of you who write these tweaking tools has cracked it.  It would be really helpful just to know that someone have confident knowledge that it either works or doesn't on a particular kernel version.

**Comment by ilya-zlobintsev** [comment]
Given the behaviour you describe and the issue in the drm repo, it is indeed not supported by the driver. All of the tweaking tools rely on this SysFS interface, and if the driver doesn't react to values being written into the files, there's not much that the utility can do about it.
Also, I don't believe that amdgpu-pro would help the situation either, as far as I'm aware it's just the userspace layer, while the SysFS is exposed by the kernel driver.

Unfortunately it is quite common for tweaking functionality to not be available on Linux for several months after the release of a new GPU generation. This was the case with previous generations too. There's not much you can do about it except wait until it gets added to the kernel.

**Comment by PorcelainMouse** [comment]
Okay.  I understand.  Thanks for your help.

It's really surprising, though. It's been more than 6 months.  That's longer than I thought was typical, but I guess I don't usually buy this new a product, so I don't really have 1st-hand experience with it.
