### ISSUE TITLE
"Enable Overclocking" does not take effect until initramfs regeneration

### ISSUE THREAD

**Issue by ilya-zlobintsev** [ilya-zlobintsev/LACT#190]
Enabling overclocking creates a file with amdgpu driver options in `/etc/modprobe.d`. In order for these options to be applied, they have to be loaded early in the boot process at the initramfs stage. At least on Arch, these settings are not included into initramfs until it is regenerated (either manually or via a kernel update). This should at least be mentioned in LACT (ideally handled automatically), also need to check what the behaviour is on other distros.

Workaround for arch-based systems (assuming the default initramfs generator is used): run `mkinitcpio -P` after clicking "enable overclocking".

**Comment by spajdrEX** [comment]
I'm using endeavourOS with Kernel 6.5RC3 and even when enabled overclocking I don't have option to change anything on my 7900XTX.

amdgpu.ppfeaturemask=0xffffffff is added to boot parameter (Corectrl shows some settings, except for FAN control which does nothing)

**aug 01 18:20:53 spajdre-linux systemd[1]: Started AMDGPU Control Daemon.
aug 01 18:20:53 spajdre-linux lact[745]: 2023-08-01T16:20:53.160942Z  INFO lact_daemon::socket: listening on "/var/run/lactd.sock"
aug 01 18:20:53 spajdre-linux lact[745]: 2023-08-01T16:20:53.182960Z  INFO lact_daemon::server::handler: initialized 1 GPUs
aug 01 18:20:53 spajdre-linux lact[745]: 2023-08-01T16:20:53.686081Z ERROR lact_daemon::server::gpu_controller: could not set fan speed: io error: Invalid argument (os error 22), disabling fan control**

**1002:744C-1849:5304-0000:2d:00.0 (Navi 31 [Radeon RX 7900 XT/7900 XTX])**

**GPU Vendor: Advanced Micro Devices, Inc. [AMD/ATI]
GPU Model: Navi 31 [Radeon RX 7900 XT/7900 XTX]
Driver in use: amdgpu
VBIOS version: 113-D70201-810009 [2022/11/29 01:30]
Link: LinkInfo { current_width: Some("16"), current_speed: Some("16.0 GT/s PCIe"), max_width: Some("16"), max_speed: Some("16.0 GT/s PCIe") }**

**Comment by ilya-zlobintsev** [comment]
This is likely related to overdrive support on 7000 series GPUs being new/incomplete, and not due to it not being enabled (if you've specified the overclocking feature mask as a boot option it's always applied)

Could you post the output of
```
ls /sys/class/drm/card*/device/
cat /sys/class/drm/card*/device/pp_od_clk_voltage
```

**Comment by spajdrEX** [comment]
[spajdrex@spajdre-linux ~]$ cat /sys/class/drm/card*/device/**pp_od_clk_voltage**
OD_SCLK:
0: 500Mhz
1: 3005Mhz
OD_MCLK:
0: 97Mhz
1: 1250MHz
OD_VDDC_CURVE:
0: 0mv
1: 0mv
2: 0mv
3: 0mv
4: 0mv
5: 0mv
OD_RANGE:
SCLK:     500Mhz       5000Mhz
MCLK:      97Mhz       1500Mhz
VDDC_CURVE:    -450mv          0mv

Also adding what is shown by corectrl (fan control does not work at all) thanks for checking :-)
![corectrl](https://github.com/ilya-zlobintsev/LACT/assets/60613263/81525320-7fb2-4fb1-8495-fad5d5221919)
![device](https://github.com/ilya-zlobintsev/LACT/assets/60613263/2b04e1e9-aff8-4bda-9075-aec8bfdaa793)

**Comment by ilya-zlobintsev** [comment]
@spajdrEX sorry for taking a long time to get back to this, basic overclocking should now work.

**Comment by ilya-zlobintsev** [comment]
Initramfs generation implemented for arch (mkinitcpio) and debian-based systems
