### ISSUE TITLE
Arch version not working

### ISSUE THREAD

**Issue by massatt212** [ilya-zlobintsev/LACT#191]
Cannot build or make lact on arch, can you upload .tar.zst installer please, it works really well on gamescope-session, unlike corectrl, which only works in desktop mode

**Comment by ilya-zlobintsev** [comment]
Can you explain what exactly isn't working? Are you building the AUR package? What's the error?

**Comment by ilya-zlobintsev** [comment]
You can now download prebulit packages from the releases page: https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build

Though building it from AUR is still the main way to get LACT on arch.
