### ISSUE TITLE
Old field values persist in GUI after changing  GPU selection

### ISSUE THREAD

**Issue by terminatorul** [ilya-zlobintsev/LACT#193]
Hello

I used 0.4.4 .rpm package, and when I open the GUI to the Information tab, then change the currently selected GPU from the top,  field values from the previous GPU persist and are shown for the newly selected GPU.

In the images bellow my RTX 3090 ASIC Name shows up as "Polaris 10" , which is obviously the value from my Radeon RX 580 card. Same for other fields like VRAM Type, VRAM bandwidth, CPU accessible VRAM.

![image](https://github.com/ilya-zlobintsev/LACT/assets/378924/bc67b886-aa03-4726-98b3-6f63fdf6a905)
![image](https://github.com/ilya-zlobintsev/LACT/assets/378924/94852a91-d433-471d-8a3e-65873fbe0caa)

**Comment by ilya-zlobintsev** [comment]
Fixed in https://github.com/ilya-zlobintsev/LACT/commit/2b77a31c76c5c95816d1d56020154f85ef17d76e, please try the the package from the [test release](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build)
