### ISSUE TITLE
hard system crashes after downgrading kernel and kernel headers to 6.3.9

### ISSUE THREAD

**Issue by iceman42** [ilya-zlobintsev/LACT#197]
bit of a weird one this, I've been using lact for about 6 months with no issues, but recently I had an issue with vram clocks being stuck at 96Mhz so downgraded the kernel (linux and linux-zen) and their headers to 6.3.9. Now I get hard system crashes on login if the lact daemon is enabled on startup, but if i enable it manually after login everything works fine.

The crashes are different for the different kernels too, if i boot into zen with the daemon enabled the screen goes blank and no graphical output is detected. Output for journalctl -u lactd:

Sep 26 09:39:45 wh-beast systemd[1]: Started AMDGPU Control Daemon.
Sep 26 09:39:45 wh-beast lact[1343]: 2023-09-26T08:39:45.113827Z  INFO lact_daemon::socket: listening on "/var/run/lactd.sock"
Sep 26 09:39:45 wh-beast lact[1343]: 2023-09-26T08:39:45.139782Z  INFO lact_daemon::server::handler: initialized 1 GPUs
Sep 26 09:39:45 wh-beast lact[1343]: 2023-09-26T08:39:45.140127Z ERROR lact_daemon::server::handler: could not apply existing config for gpu 1002:73BF-1DA2:E438-0000:2d:00.0: io error: No such file or directory (os error 2)
Sep 26 09:39:45 wh-beast lact[1343]: Could not read file pp_od_clk_voltage

Whereas if i boot into linux the screen goes blank and the fans spin up to 100%.  Output for journalctl -u lactd:
Sep 26 10:03:09 wh-beast systemd[1]: Started AMDGPU Control Daemon.
Sep 26 10:03:10 wh-beast lact[1375]: 2023-09-26T09:03:10.004674Z  INFO lact_daemon::socket: listening on "/var/run/lactd.sock"
Sep 26 10:03:10 wh-beast lact[1375]: 2023-09-26T09:03:10.027229Z  INFO lact_daemon::server::handler: initialized 1 GPUs
Sep 26 10:03:20 wh-beast lact[1375]: thread 'main' panicked at 'No current temp', lact-daemon/src/server/gpu_controller/fan_control.rs:16:36
Sep 26 10:03:20 wh-beast lact[1375]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Here are my system stats:
OS: Garuda Linux x86_64
Host: MS-7C92 1.0
Kernel: 6.3.9-zen1-1-zen
Uptime: 1 hour, 3 mins
Packages: 1704 (pacman)[stable]
Shell: fish 3.6.1
Resolution: 3440x1440
WM: Sway (Wayland)
Theme: Nordic-darker [GTK2/3]{?3} {3} [Plasma], {?}{7}
Icons: Tela-circle-dark [GTK2/3]
Terminal: alacritty 0.12.2
Terminal Font: JetbrainsMonoNL 16
CPU: AMD Ryzen 9 3950X (32) @ 4.76123 GHz
GPU: AMD Radeon RX 6800 XT
Memory: 7.30 GiB / 31.27 GiB

Looking at the lactd.service file:
[Unit]
Description=AMDGPU Control Daemon
After=multi-user.target

[Service]
ExecStart=lact daemon

[Install]
WantedBy=graphical.target

I wonder if I can sort this by changing the "After" or "Install" fields? As it seems that the daemon is loading too early?

Thanks!

**Comment by ilya-zlobintsev** [comment]
This indeed looks like the daemon gets started too early. Currently the daemon waits until there is at least one GPU present in the sysfs, but I'm guessing this is not enough to determine that the GPU is fully initialized.

Could you try adding `ExecStartPre=sleep 5` to the Service section of the unit to see if it works as a workaround?

**Comment by iceman42** [comment]
Hi there, sorry I haven't had time recently to play around until today. Here's the current status: 

Earlier on I was on the 6.3.9 zen kernel, and having lactd service enabled at startup (with your ExecStartPre=sleep 5 line in the service file) made the fans spin up and black screen after log in, with the following in the logs:

Oct 10 18:22:45 wh-beast lact[8533]: thread 'main' panicked at 'No current temp', lact-daemon/src/server/gpu_controller/fan_control.rs:16:36

but if i left it disabled at start up, I was able to start the service once i logged in.
with the 6.3.9 (not zen) kernel, after log in the screen just goes blank and my monitor says no input detected, nothing in the logs.

I decided to try the new 6.5.6 zen and non-zen kernels. these both gave the same behaviour as the non-zen 6.3.9 - blank screen with no input detected after log in. The difference is that this time if i boot up with the service disabled, then enable it once i log in the screen (after the 5 second wait) goes blank with no input detected (zen) or artifacts and the fans spin up (zen). Again, nothing in the journalctl -u lactd logs for either of these

**Comment by ilya-zlobintsev** [comment]
Can you post your `/etc/lact/config.yaml`? This sounds like it could be applying some invalid settings. However, different behaviour between kernel versions is very weird.

You can also try removing the config file and redoing your settings.

**Comment by iceman42** [comment]
here's my /etc/lact/config.yaml file:

daemon:
  log_level: info
  admin_groups:
  - wheel
  - sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:73BF-1DA2:E438-0000:2d:00.0:
    fan_control_enabled: true
    fan_control_settings:
      temperature_key: edge
      interval_ms: 500
      curve:
        30: 0.0
        40: 0.0
        50: 0.1446613
        55: 0.1587256
        60: 0.1836969
        65: 0.27095294
        70: 0.37543055
        75: 0.52812856
        80: 0.7807118
    power_cap: 289.0
    performance_level: auto
    min_memory_clock: 674
    max_core_clock: 2600
    max_memory_clock: 1000
    voltage_offset: -130

and just if it helps, this is the /etc/modprobe.d/99-amdgpu-overdrive.conf file:

options amdgpu ppfeaturemask=0xFFF7FFFF


I'll have a go at removing the config file this evening. Thanks for your help!

**Comment by iceman42** [comment]
Ah sorry it looks like the config file didnt format properly, here you go:

```
daemon:
  log_level: info
  admin_groups:
  - wheel
  - sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:73BF-1DA2:E438-0000:2d:00.0:
    fan_control_enabled: true
    fan_control_settings:
      temperature_key: edge
      interval_ms: 500
      curve:
        30: 0.0
        40: 0.0
        50: 0.1446613
        55: 0.1587256
        60: 0.1836969
        65: 0.27095294
        70: 0.37543055
        75: 0.52812856
        80: 0.7807118
    power_cap: 289.0
    performance_level: auto
    min_memory_clock: 674
    max_core_clock: 2600
    max_memory_clock: 1000
    voltage_offset: -130
```

**Comment by ilya-zlobintsev** [comment]
Did you have any success after removing the file?

**Comment by iceman42** [comment]
Hi! I removed the file but then the application crashed on startup. I haven't had time to look at other solutions at the moment (card has a bios switch with 3 different bios) due to just being busy. But for some reason the linux, linux-zen and xanmod kernels have all been buggy for the last month or so so I'm using lts at the moment. Think I'm going to change to a different distribution soon anyway as I have had other problems with garuda so I don't know if you want to mark this as closed?

**Comment by ilya-zlobintsev** [comment]
Okay, I'll close this, feel free to reopen if you get the same problems again
