### ISSUE TITLE
Permission Denied Error when trying to change Performance Level and Power Level Mode

### ISSUE THREAD

**Issue by tjssoldier** [ilya-zlobintsev/LACT#202]
When i am trying to change  Performance Level and Power Level Mode i get this error:

```
lact[2305]: 2023-10-30T22:44:20.631759Z  INFO lact_daemon::server::handler: initialized 1 GPUs
lact[2305]: 2023-10-30T22:55:58.379407Z ERROR lact_daemon::server::handler: could not apply settings: Could not set fan control back to automatic: io error: Permission denied (os error 13)
lact[2305]: 2023-10-30T23:03:23.330050Z ERROR lact_daemon::server::handler: could not apply settings: Could not set fan control back to automatic: io error: Permission denied (os error 13)
lact[2305]: 2023-10-30T23:03:47.024258Z ERROR lact_daemon::server::handler: could not apply settings: Could not set fan control back to automatic: io error: Permission denied (os error 13)
```
I can change this settings if i use the terminal, with this commands for example: 

`echo "manual" | sudo tee /sys/class/drm/card0/device/power_dpm_force_performance_level`

and 

`echo "3" | sudo tee /sys/class/drm/card0/device/pp_power_profile_mode`

This will change the power level mode to "VIDEO", but it does not work with LACT because of the error.

System info:
OS: Debian 12 Bookworm (with kernel 6.1.0-13)
Mesa: 22.3.6
LACT: 0.4.5
Hardware: AMD Ryzen 5700U with Radeon Graphics (Vega 8)

**Comment by ilya-zlobintsev** [comment]
Just to clarify, do you have the lactd service enabled? (you can check via `systemctl status lactd`)

**Comment by tjssoldier** [comment]
```
● lactd.service - AMDGPU Control Daemon
     Loaded: loaded (/lib/systemd/system/lactd.service; enabled; preset: enabled)
     Active: active (running) since Mon 2023-10-30 22:17:51 -03; 11h ago
   Main PID: 2439 (lact)
      Tasks: 1 (limit: 8647)
     Memory: 7.8M
        CPU: 30.548s
     CGroup: /system.slice/lactd.service
             └─2439 lact daemon

```

**Comment by ilya-zlobintsev** [comment]
Fixed in https://github.com/ilya-zlobintsev/LACT/commit/df28a63678db47c75ad95ab39a0604a5096cac5b, try the test build from [here](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build)

**Comment by tjssoldier** [comment]
It's working fine now. Thanks!
