### ISSUE TITLE
Feature or advice

### ISSUE THREAD

**Issue by massatt212** [ilya-zlobintsev/LACT#203]
For systemd users we cannot over clock unless we edit the file located in /boot/loader/entries/what ever the system say your file is

and add
`options root=LABEL=frzr_root rw rootflags=subvol=deployments/chimeraos-45_65b2a8b quiet splash loglevel=3 rd.systemd.show_status=auto rd.udev.log_priority=3  ibt=off split_lock_detect=off iomem=relaxed nowatchdog amdgpu.ppfeaturemask=0xffffffff`

and it will give u overclocking features on systemd bootloader

**Comment by ilya-zlobintsev** [comment]
I'm not sure what you want to say here. LACT has a built-in option to enable overclocking that relies on creating a config file. Specifying a kernel argument in your bootloader is another way to do it.
