### ISSUE TITLE
lact crashed (sigsegv) at recent kernels (6.5/6.6)

### ISSUE THREAD

**Issue by Sfinx** [ilya-zlobintsev/LACT#204]
Card is Vega10:

```
lshw -C display
  *-display                 
       description: VGA compatible controller
       product: Vega 10 XL/XT [Radeon RX Vega 56/64]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:09:00.0
       logical name: /dev/fb0
       version: c7
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=amdgpu latency=0 resolution=5120,1440
       resources: irq:77 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:2000(size=256) memory:f0600000-f067ffff memory:f06a0000-f06bffff
```
Crashed just upon start - no tweaks or overclocking ever applied. Crash never occurred at 6.4.x kernels.

[lact-v0.4.5.amd.bug.txt](https://github.com/ilya-zlobintsev/LACT/files/13236213/lact-v0.4.5.amd.bug.txt)

**Comment by ilya-zlobintsev** [comment]
That is extremely weird. I'm also running a Vega 56 on the 6.5 kernel, and I cannot reproduce this.
Do the GPU reset errors occur when LACT is not enabled? And is LACT enabled to start on system boot, or do you start it later manually?

**Comment by Sfinx** [comment]
The reset with kernels > 6.4 is occured even when LACT is not launched but very rare (once per day) but it _always_ accured when I launch LACT. I pretty sure this is real kernel problem but submitting and waiting for bug report at ketnel.org can take years

**Comment by Sfinx** [comment]
Can supply any additional info (straces or so)

**Comment by ilya-zlobintsev** [comment]
Please try the following:
- Install the latest build from the master branch (either from the [test release](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build) or using the lact-git AUR package if you are on an arch-based distro)
- Edit `/etc/lact/config.yaml` and set `log_level: trace` under daemon. If it doesn't exist, here's the minimal required contents:
```
daemon:
  log_level: trace
  admin_groups:
  - wheel
  - sudo
```
- Start the service (`systemctl start lactd`)
- Run the gui with `lact gui --log-level trace`

This should provide detailed logs (in both the daemon and gui) for what exactly is happening during the crash

**Comment by Sfinx** [comment]
Daemon do not starts. Any config example exists ?

```
lact daemon
Error: Could not deserialize config

Caused by:
    missing field `gpus`
```

**Comment by Sfinx** [comment]
Added 

```
gui: {}
```

And it starts. In short: lact sigsegv's when no daemon is launched. No sigsegv with daemon. GPU crash occurring in both cases - as with daemon as without. Logs attached
[lact-daemon.log](https://github.com/ilya-zlobintsev/LACT/files/13262415/lact-daemon.log)
[lact-gui-with-daemon.log](https://github.com/ilya-zlobintsev/LACT/files/13262416/lact-gui-with-daemon.log)
[dmesg-with-daemon.txt](https://github.com/ilya-zlobintsev/LACT/files/13262417/dmesg-with-daemon.txt)
[lact-gui-no-daemon.log](https://github.com/ilya-zlobintsev/LACT/files/13262418/lact-gui-no-daemon.log)
[dmesg-no-daemon.txt](https://github.com/ilya-zlobintsev/LACT/files/13262419/dmesg-no-daemon.txt)

**Comment by Sfinx** [comment]
BTW: 
[ubsan.txt](https://github.com/ilya-zlobintsev/LACT/files/13262427/ubsan.txt)
Kernel build with UBSAN shows warnings in amdgpu driver

**Comment by Sfinx** [comment]
> BTW: Kernel build with UBSAN shows warnings in amdgpu driver
> 
> [ubsan.txt](https://github.com/ilya-zlobintsev/LACT/files/13262427/ubsan.txt)

Ignore this - it is false warning and fix is already present in 6.7

**Comment by Sfinx** [comment]
Can't reproduce GPU crash with amdgpu.mcbp=0 kernel cmd option

**Comment by ilya-zlobintsev** [comment]
Do you still get a segfault with the kernel option that resolves the crash? The application logs seem perfectly normal in all of the scenarios - even in `lact-gui-no-daemon` where there is a segfault in dmesg. Does the segfault happen after the log you posted?
The UBSAN log mentions an error when reading the power table - this would make sense, as both the standalone gui and gui with daemon try to read it to display clocks info. If the kernel crashes from that, there's not much that can be done from LACT's side to avoid it.

**Comment by Sfinx** [comment]
The lact (0.4.6) sigsegv's just after launch when no daemon present - see the start of dmesg-no-daemon.txt :

```
[Nov 6 06:09] lact[16171]: segfault at 7fddcf1ff910 ip 00007fdde1c9651b sp 00007fdddddda610 error 4 in libc.so.6[7fdde1c28000+195000] likely on CPU 0 (core 0, socket 0)
[  +0.000017] Code: 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 48 85 ff 0f 84 55 01 00 00 <8b> 87 d0 02 00 00 48 89 fb 85 c0 0f 88 44 01 00 00 48 39 bf 28 06
[  +0.500052] lact[16181]: segfault at 7fddcf1ff910 ip 00007fdde1c9651b sp 00007fdddddd8ea0 error 4 in libc.so.6[7fdde1c28000+195000] likely on CPU 15 (core 7, socket 0)
[  +0.000016] Code: 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 48 85 ff 0f 84 55 01 00 00 <8b> 87 d0 02 00 00 48 89 fb 85 c0 0f 88 44 01 00 00 48 39 bf 28 06
```

Not sure if the SIGSEGV event can be catched by lact - usually process is killed by kernel so you will not see anything at app logs.

The UBSAN kernel warnings are false alram and you can ignore them. The kernel GPU driver do not crash with amdgpu.mcbp=0

The sad problem is that this setting is set to 1 at recent kernels - this is why I did not see it with 6.4.x. Seems like nobody tested the driver before this change.

**Comment by ilya-zlobintsev** [comment]
If this is still relevant: does this occur with recent kernel (6.7) and lact (0.5.2) versions?

**Comment by Sfinx** [comment]
App still crashes when no daemon present, kernel v6.7.3:

```
[Feb 5 06:51] lact[523318]: segfault at 79968bc00910 ip 000079969389651b sp 00007996803fa340 error 4 in libc.so.6[799693828000+195000] likely on CPU 0 (core 0, socket 0)
[  +0.000018] Code: 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 48 85 ff 0f 84 55 01 00 00 <8b> 87 d0 02 00 00 48 89 fb 85 c0 0f 88 44 01 00 00 48 39 bf 28 06
[  +0.623788] lact[523329]: segfault at 79968bc00910 ip 000079969389651b sp 00007996803f9040 error 4 in libc.so.6[799693828000+195000] likely on CPU 14 (core 7, socket 0)
[  +0.000017] Code: 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 48 85 ff 0f 84 55 01 00 00 <8b> 87 d0 02 00 00 48 89 fb 85 c0 0f 88 44 01 00 00 48 39 bf 28 06
```

But amdgpu driver do not crash anymore as amdgpu maintainers reverted back amdgpu.mcbp=1 kernel option.

**Comment by ilya-zlobintsev** [comment]
Could you do the following:
- Run the app with debuginfo (clone this repo and simply run `cargo run`, information about required dependencies [here](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#building-from-source))
- Check the core dump of when it crashes with `coredumpctl info -1 lact`

**Comment by Sfinx** [comment]
[dump.txt](https://github.com/ilya-zlobintsev/LACT/files/14161600/dump.txt)

**Comment by ilya-zlobintsev** [comment]
Could you also check `strace -f ./target/debug/lact`?

**Comment by Sfinx** [comment]
[strace.txt](https://github.com/ilya-zlobintsev/LACT/files/14164562/strace.txt)

**Comment by ilya-zlobintsev** [comment]
Please try the `segfault-fix-attempt` branch and tell me if it helps (based on the strace, it should fix the issue)

**Comment by Sfinx** [comment]
Confirming - no segfaults any more in segfault-fix-attempt branch

**Comment by Sfinx** [comment]
Closing
