### ISSUE TITLE
Voltage and clock control not available for RX 7900XT

### ISSUE THREAD

**Issue by neliavaal** [ilya-zlobintsev/LACT#205]
Voltage and clock control is unavailable. Power management works
Also I don't have /sys/class/drm/card0/device/pp_od_clk_voltage 

```

ls /sys/class/drm/card*/device/
/sys/class/drm/card0/device/:
aer_dev_correctable	   dma_mask_bits     ip_discovery	      msi_bus				 pp_dpm_vclk		resource0_wc
aer_dev_fatal		   driver	     irq		      msi_irqs				 pp_features		resource2
aer_dev_nonfatal	   driver_override   link		      numa_node				 pp_force_state		resource2_resize
apu_thermal_cap		   drm		     local_cpulist	      pcie_bw				 pp_mclk_od		resource2_wc
ari_enabled		   enable	     local_cpus		      pcie_replay_count			 pp_num_states		resource4
boot_vga		   fw_version	     max_link_speed	      power				 pp_power_profile_mode	resource5
broken_parity_status	   gpu_busy_percent  max_link_width	      power_dpm_force_performance_level  pp_sclk_od		revision
class			   gpu_metrics	     mem_busy_percent	      power_dpm_state			 pp_table		rom
config			   graphics	     mem_info_gtt_total       power_state			 psp_vbflash		subsystem
consistent_dma_mask_bits   hdcp_srm	     mem_info_gtt_used	      pp_cur_state			 psp_vbflash_status	subsystem_device
consumer:pci:0000:09:00.1  hwmon	     mem_info_preempt_used    pp_dpm_dcefclk			 remove			subsystem_vendor
consumer:pci:0000:09:00.2  i2c-4	     mem_info_vis_vram_total  pp_dpm_dclk			 rescan			thermal_throttling_logging
consumer:pci:0000:09:00.3  i2c-5	     mem_info_vis_vram_used   pp_dpm_fclk			 reset			uevent
current_link_speed	   i2c-6	     mem_info_vram_total      pp_dpm_mclk			 reset_method		unique_id
current_link_width	   i2c-7	     mem_info_vram_used       pp_dpm_pcie			 resource		vbios_version
d3cold_allowed		   i2c-8	     mem_info_vram_vendor     pp_dpm_sclk			 resource0		vendor
device			   i2c-9	     modalias		      pp_dpm_socclk			 resource0_resize

/sys/class/drm/card0-DP-1/device/:
card0-DP-1  card0-DP-2	card0-DP-3  card0-HDMI-A-1  dev  device  power	subsystem  uevent

/sys/class/drm/card0-DP-2/device/:
card0-DP-1  card0-DP-2	card0-DP-3  card0-HDMI-A-1  dev  device  power	subsystem  uevent

/sys/class/drm/card0-DP-3/device/:
card0-DP-1  card0-DP-2	card0-DP-3  card0-HDMI-A-1  dev  device  power	subsystem  uevent

/sys/class/drm/card0-HDMI-A-1/device/:
card0-DP-1  card0-DP-2	card0-DP-3  card0-HDMI-A-1  dev  device  power	subsystem  uevent
```

`Linux eb2ad5c8 6.6.0 #1 SMP PREEMPT_DYNAMIC Mon Oct 30 09:46:52 CET 2023 x86_64 x86_64 x86_64 GNU/Linux`

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

![Screenshot from 2023-11-03 17 09 54](https://github.com/ilya-zlobintsev/LACT/assets/95719224/7a21044b-dbe8-4b95-a3b1-23d701fc1150)

![Screenshot from 2023-11-03 17 10 25](https://github.com/ilya-zlobintsev/LACT/assets/95719224/a4244a47-ec12-419d-baec-8f80b89583a5)

**Comment by ilya-zlobintsev** [comment]
Unfortunately overdrive is still not available for RDNA3 on the stable kernel: https://gitlab.freedesktop.org/drm/amd/-/issues/2840#note_2079945

**Comment by neliavaal** [comment]
Got you. Waiting for 6.7 then.
Great software!

**Comment by jpsalm** [comment]
Just a heads up, this has landed in linux 6.7-rc2.

**Comment by KyunLFA** [comment]
Just gonna drop some info here, so anyone can take it as they will.

CachyOS Linux (Arch Base, x86-64-v4, glibc 2.38) | Sapphire PURE Radeon RX 7800 XT | Linux-next 04/Dec | Mesa-devel 24.0 commit b7517aec9ee665c7b4c8c4629deeb0e34925b777 | Linux-firmware-git 04/Dec | LLVM 18 commit c6381615ef9bc869a708ab8f786c4350f7e00ee7 | Ryzen R9 7900X

- GPU does not want to leave zero RPM mode even on "successful" fan curve control according to https://gitlab.freedesktop.org/drm/amd/-/issues/2402#note_2184713

- Power limit half-broken. Limited to 244W for some reason out of 253W. Set according to https://docs.kernel.org/next/gpu/amdgpu/thermal.html

- Core voltage curve offset extremely limited, can only undervolt massively (limit is -450mv) but not overvolt at all. Also set according to html doc above

- Gravitymark performance very unimpressive at under 30 FPS 1080p on 1,000,000 asteroids (normal?), still doesnt ramp fans until after uncomfortably sitting at 100% utilization for a good bit. Temperature is very low for stress (?) and boosting conservatively (also ?) *definitely* seems power/voltage bound (possible regression on Mesa-devel or something went funky with the mesa compile*?)

- Tried: LACT, CoreCtrl, Tuxclocker (none work at all besides setting clocks for GPU and VRAM and power state profiles; fanspeed, voltage, power limit, all broken)

- Using any OC tool of the above spams in dmesg: `amdgpu: manual fan speed control should be enabled first` and resets custom fanspeed

At this point I can say confidently that GPU OC/OV/FANSPEED(!!!) should be marked BROKEN on all tools even on bleeding edge kernels, drivers and firmware unless someone can attest they got a different result.

*I've already eliminated problem FLAGS from mesa causing crashes (except one with Yuzu emulator FPS unlock on Breath of the Wild, though might be an issue with my Yuzu setup, will update later), but might still be over-optimized and causing the bad gravitymark scores, will test Windows 11 shortly to confirm

**Comment by jpsalm** [comment]
I’m back on 6.6 right now but in my brief testing both fan controls and voltage controls seemed to be mostly working.

I wasn’t using LACT but the OD interface itself: https://docs.kernel.org/gpu/amdgpu/thermal.html

All the fan stuff has moved to a new interface, so LACT and other wrappers won’t work until they’re updated.
One thing I was curious about was I seemingly only had two p states in pp_od_clk_voltage but not sure if that’s a design decision from AMD or not.  It seems the interface had changed from the original set of patches, in that there was a single voltage offset you could apply for all p states rather than one each IIRC.

**Comment by neliavaal** [comment]
@ilya-zlobintsev  
May I ask you if the power usage limit was changed in LACT? - now it allows to go as low as 231 Wt.
Previously as was able to lower the limit to at least 199 Wt (maybe even less)
I know the voltage offset allows to reduce the power consumption but I wanted to clarify if the change is in LACT or in the kernel.
I'm on 6.7.0-rc3 and LACT 0.5.0 from release git

**Comment by ilya-zlobintsev** [comment]
@neliavaal there was a change in 0.5.0 where the GUI now properly enforces the allowed minimum power cap. However, I don't think values outside of the allowed range would be handled properly by the driver either way.

You can edit `/etc/lact/config.yaml`, set the limit manually, restart the service and check if the limit actually works. This would be the same as setting a lower value using the GUI previously.

**Comment by ilya-zlobintsev** [comment]
Overclocking settings have been tested to work on a 7900xt on the latest master build.
