### ISSUE TITLE
[Feature] Steamdeck Plugin

### ISSUE THREAD

**Issue by massatt212** [ilya-zlobintsev/LACT#206]
have you tested this on a steamdeck, cause it works on chimera and bazzite also nobara, you should make a steam plugin

**Comment by ilya-zlobintsev** [comment]
Implementing a steam plugin is out of scope for this project. You can, however, make one using the [API](https://github.com/ilya-zlobintsev/LACT/blob/master/API.md) that the LACT daemon provides.
