### ISSUE TITLE
LACT sometimes completely disables power limit (6900XT)

### ISSUE THREAD

**Issue by adolfintel** [ilya-zlobintsev/LACT#207]
If the power limit is set to a value that's too low for the power state that the card is currently in, it seems that the driver completely disables the power limit, causing the card to have a spike in power consumption (I've seen it go as high as 420w up from a 293w TDP) until the card leaves that state and then it is applied correctly.

This can be easily replicated by setting the power limit while running any GPU intensive application that will keep the card at its highest power state (demonstrated in the video using stable diffusion) and can potentially lead to damage if running something like furmark which is not memory-bound.

OS: Arch Linux, Kernel 6.6.1, GPU: 6900XT

Here's a video of the problem:
[plbug.webm](https://github.com/ilya-zlobintsev/LACT/assets/16307689/bab92674-8010-46b4-b579-e54fd095e529)

**Comment by ilya-zlobintsev** [comment]
As you've noted, this is the behaviour of the driver, which LACT has no direct control of. 
However, i think there can be a workaround: if the performance mode would be set to "lowest clocks" when a new power limit is applied, and then reverted back to whatever it was before (most likely "automatic"), then in theory this issue would be avoided.

Could you test if doing this manually avoids the problem on your system? Set the performance level to lowest together with the new power limit, apply, and then change it back to automatic. If it does help, then I'll implement it to be done automatically when setting the limit.

**Comment by ilya-zlobintsev** [comment]
I don't think there's a good way to "suspend" the GPU.
Maybe there could be a wait interval until the clockspeed or power usage come down, though I'm not sure if it would be a good user experience. I'll see if i can reproduce this on my machine.

Kernel issues are generally reported here: https://gitlab.freedesktop.org/drm/amd

**Comment by adolfintel** [comment]
Reported it: https://gitlab.freedesktop.org/drm/amd/-/issues/2992

**Comment by ilya-zlobintsev** [comment]
@adolfintel if this is still relevant: could you try building the `power-limit-clockdown` branch and see if it solves the issue? I've added a workaround that waits until the GPU enters the lowest power state before applying the limit.

**Comment by adolfintel** [comment]
@ilya-zlobintsev that works! Good job :)
