### ISSUE TITLE
App is using light theme when system is dark theme on Fedora 39

### ISSUE THREAD

**Issue by ZVNexus** [ilya-zlobintsev/LACT#213]

**Comment by ilya-zlobintsev** [comment]
LACT uses GTK4, but not libadwaita, and follows system theming. Looks like Fedora does not ship the plain GTK4 dark theme by default for some reason. You have to install `gnome-themes-extra` and `gnome-tweaks`, and set the "legacy applications" style to Adwaita-dark.

**Comment by ilya-zlobintsev** [comment]
Update: libadwaita builds are now provided as an option [link](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build)

**Comment by arrowgent** [comment]
had to set this to enable darkmode in gtk4

```
# ~/.config/gtk-4.0/settings.ini
[Settings]
gtk-application-prefer-dark-theme = true
```
