### ISSUE TITLE
Installation notes for openSUSE

### ISSUE THREAD

**Issue by gladly-hyphenated-21** [ilya-zlobintsev/LACT#216]
Hi there

I've just finished installing this on my openSUSE box, so I'm here to briefly explain the problems I had and my solutions to them.

**blueprint-compiler**
openSUSE [ships with version 0.6.0](https://build.opensuse.org/package/show/openSUSE:Factory/blueprint-compiler), you will need to install 0.10.0 from [source](https://gitlab.gnome.org/jwestman/blueprint-compiler).

**make compiler complaints**
I've gone through this here. Turns out you need several other packages. The zypper command is: `sudo zypper install rust gtk4 pkg-config make hwdata libdrm libdrm-devel libdrm libdrm-tools lshw`

**won't connect to the daemon**
I needed to do two things: 
1) Edit `/etc/lact/config.yaml` and add  `root` to the admin_groups
2) login as root from the login screen (yes, the gui; yes, you have to log out) and search 'lact' in the command bar. Then right click on the application when it comes up, and click 'edit application'. From there, change the permissions all to 'can view & modify' for all groups. Make sure the ownership as `user: root` and `Group: root` stay the same.
3) start the daemon normally, reboot, and enjoy.

That's what it took for me to fix it. Hope this helps someone else.

**Comment by goryramsy** [comment]
**For search engines:**

  = note: /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -ldrm: No such file or directory
          /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -ldrm_amdgpu: No such file or directory
          collect2: error: ld returned 1 exit status

Compiling lact v0.5.0 (/home/automation/LACT/lact)

error: could not compile `lact` (bin "lact") due to previous error
make: *** [Makefile:5: build-release] Error 101

**Comment by ilya-zlobintsev** [comment]
Regarding the blueprint-compiler version: I'm guessing this is on the stable version of OpenSUSE, not tumbleweed, right?

As for the permissions issue: this workaround is definitely not something that should be required.
The way the `admin_groups` setting works is that it finds the first group from the list, and uses it as the group that has access to the socket. On most desktop systems there is usually either the `wheel` or `sudo` group present, with the main user being a member of it. This works in most cases. I'm guessing that on your system your user is not a member of the first group that was found.

Can you check if the connection works without the workaround if the `admin_groups` only lists your main user, and nothing else? You can check the actual permissions that the socket has with `stat /var/run/lactd.sock`.

**Comment by ilya-zlobintsev** [comment]
There's now a prebuilt package provided for OpenSUSE as well as information about configuring the socket permissions in the README.
