### ISSUE TITLE
VBIOS Version key doesn't make sense

### ISSUE THREAD

**Issue by superm1** [ilya-zlobintsev/LACT#219]
I checked this on a Lenovo Z13.

The value populated in VBIOS version for my system doesn't make sense.  The string that is populated is what is used to describe _what_ the VBIOS applies to and the date; not the version.

In LACT on my system it's `113-REMBRANDT-X37 [2022/04/12 06:21]`
Comparing fwupdt:
```shell
# fwupdtool get-devices --plugins amd-gpu
LENOVO 21D2SIT061
│
└─Graphics Processing Unit (GPU):
      Device ID:          2287ee908298807e95f89a9b7c1a435c1a634e33
      Summary:            Rembrandt Generic VBIOS
      Current version:    032.017.000.055.000000
      Vendor:             Advanced Micro Devices, Inc. [AMD/ATI] (PCI:0x1002)
      GUID:               6d1757cb-7371-5d9a-9b7a-4be4b21ef0b9 ← AMD\113-REMBRANDT-X37
      Device Flags:       • Internal device
```

You can see the value `113-REMBRANDT-X37` is used to describe how fwupd would match the hardware against any payloads posted to LVFS.  The version string comes from  [DRM_IOCTL_AMDGPU_INFO](https://github.com/fwupd/fwupd/blob/1.9.8/plugins/amd-gpu/fu-amd-gpu-device.c#L134).

**NOTE**: if you're checking on reproducing in fwupd, there was a bug in 1.9.9 release that prevents it working.  You can take https://github.com/fwupd/fwupd/commit/e90fdd56704d04af882b7f11a8bc022e2d615d37 to solve it.

**Comment by ilya-zlobintsev** [comment]
Fixed in https://github.com/ilya-zlobintsev/LACT/commit/e98df054debdbb2ccad7e3f8dc53979a7c3fdb27
The value that was used previously was taken from the SysFS, e.g. `/sys/class/drm/card1/device/vbios_version`. It will still be used as a fallback when DRM is not available.

**Comment by superm1** [comment]
Thanks!

JFYI it was also "fixed" in sysfs (https://github.com/torvalds/linux/commit/7748ce5b69581325cae40c2134088820f0957902) until there were regressions reported from tools that expected the way it behaved before so it got reverted (https://github.com/torvalds/linux/commit/06cce38ef51fc101402a0b02fca6e69c2e15ff3c).

At least LACT will show the right value when it's compiled with DRM support.
