### ISSUE TITLE
How to disable 0 RPM mode

### ISSUE THREAD

**Issue by abrasmelin** [ilya-zlobintsev/LACT#229]
Hello I am a 7900XT user. I can not control the fan curve with LACT. Fan Speed always shows 0 RPM. Is there a work around for this ? Thanks.

**Comment by ilya-zlobintsev** [comment]
Fan control is not currently supported on stable kernel versions on RDNA3. You'll have to wait until Linux 6.7.

**Comment by abrasmelin** [comment]
I have installed Linux mainline kernel 6.7 and it is still not working.

**Comment by ilya-zlobintsev** [comment]
Looks like it's a bit more complicated than just requiring a 6.7 kernel, it also doesn't support custom fan speed on the hardware level, and instead uses a new interface for custom fan curves: https://gitlab.freedesktop.org/drm/amd/-/issues/2402

Could you post the output of `cat /sys/class/drm/card*/device/gpu_od/fan_ctrl/*`

**Comment by abrasmelin** [comment]
cat: '/sys/class/drm/card*/device/gpu_od/fan_ctrl/*': No such file or directory

**Comment by robzombie91** [comment]
I have a 7800 xt and same thing, using the linux-mainline kernel

OD_ACOUSTIC_LIMIT:
2450
OD_RANGE:
ACOUSTIC_LIMIT: 500 3100
OD_ACOUSTIC_TARGET:
2200
OD_RANGE:
ACOUSTIC_TARGET: 500 3100
OD_FAN_CURVE:
0: 0C 0%
1: 0C 0%
2: 0C 0%
3: 0C 0%
4: 0C 0%
OD_RANGE:
FAN_CURVE(hotspot temp): 25C 100C
FAN_CURVE(fan speed): 20% 100%
FAN_MINIMUM_PWM:
20
OD_RANGE:
MINIMUM_PWM: 20 100
FAN_TARGET_TEMPERATURE:
95
OD_RANGE:
TARGET_TEMPERATURE: 25 110

**Comment by ilya-zlobintsev** [comment]
I've added support for configuring the new settings of the automatic fan curve (target temperature, minimum fan speed and target/limit speed). Support for full-fledged custom fan curves will be added later.

**Comment by ilya-zlobintsev** [comment]
Setting custom curves is also supported now.

**Comment by ilya-zlobintsev** [comment]
Closing as the relevant functionality has been added.
