### ISSUE TITLE
Controlling GPU via allowing specific P-states

### ISSUE THREAD

**Issue by murlakatamenka** [ilya-zlobintsev/LACT#23]
Hi, I have R9 290 GPU and it doesn't support fine tuning Polaris+ cards have, i.e. setting precise clocks and voltages via `/sys/class/drm/card0/device/pp_od_clk_voltage` SysFS, it simply doesn't exist for my GPU.

However, I can still control the card via enabling specific p-states (https://kernel.org/doc/html/latest/gpu/amdgpu.html#pp-dpm):

```sh
cd /sys/class/drm/card0/device

echo manual | sudo tee power_dpm_force_performance_level
# allow core clocks from the first 3 p-states
echo 0 1 2  | sudo tee pp_dpm_sclk
# allow 2 (of 3 in my case) memory clocks
echo 0 1    | sudo tee pp_dpm_mclk
```
Do you think you can support GPU control in such way?

**Comment by ilyazzz** [comment]
Having simple on/off switches for p-states as a fallback when pp_od_clk_voltage isn't there (which is also newer cards when the overclock kernel argument isn't specified) should be possible. I'll look into it.

Also, are you sure you're using the amdgpu driver? GCN 1/2 cards use the older radeonsi by default.

**Comment by murlakatamenka** [comment]
> Also, are you sure you're using the amdgpu driver? GCN 1/2 cards use the older radeonsi by default.

Yes, I followed Arch Wiki back in the day:

`/etc/modprobe.d/amdgpu.conf`

```sh
blacklist radeon

options amdgpu cik_support=1
options amdgpu si_support=0

options amdgpu ppfeaturemask=0xffffffff

options radeon cik_support=0
options radeon si_support=0
```

```sh
> lspci -k | rg -B2 amdgpu
09:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290/390]
	Subsystem: XFX Pine Group Inc. Device 9395
	Kernel driver in use: amdgpu
	Kernel modules: radeon, amdgpu
```
