### ISSUE TITLE
Crash after trying to fix value on overcloking panel

### ISSUE THREAD

**Issue by nightwolf-1** [ilya-zlobintsev/LACT#230]
It crash probobly because of the DRM version is 1.6.0 but my driver need 3.x.x.

This is the output log i have retrive whit journalctl

déc. 19 17:08:50 archlinux systemd[1]: Started AMDGPU Control Daemon.
déc. 19 17:08:50 archlinux lact[775]: 2023-12-19T16:08:50.737581Z  INFO lact_daemon: service started too early, waiting 4.4 seconds
déc. 19 17:08:55 archlinux lact[775]: 2023-12-19T16:08:55.109655Z  INFO lact_daemon::socket: listening on "/var/run/lactd.sock"
déc. 19 17:08:55 archlinux lact[775]: amdgpu_device_initialize: DRM version is 1.6.0 but this driver is only compatible with 3.x.x.
déc. 19 17:08:55 archlinux lact[775]: 2023-12-19T16:08:55.109741Z  WARN lact_daemon::server::gpu_controller: Could not get DRM handle: Could not open drm handle, error code -9
déc. 19 17:08:55 archlinux lact[775]: 2023-12-19T16:08:55.130592Z  INFO lact_daemon::server::handler: initialized 2 GPUs
déc. 19 17:10:27 archlinux lact[775]: 2023-12-19T16:10:27.502991Z  INFO lact_daemon::server::handler: saving updated config
déc. 19 17:10:27 archlinux lact[775]: 2023-12-19T16:10:27.503155Z  INFO lact_daemon::server::handler: saving updated config
déc. 19 17:10:27 archlinux lact[775]: 2023-12-19T16:10:27.509024Z  INFO lact_daemon::server::handler: saving updated config
déc. 19 17:10:27 archlinux lact[775]: 2023-12-19T16:10:27.509131Z  INFO lact_daemon::server::handler: saving updated config
déc. 19 17:10:30 archlinux lact[775]: 2023-12-19T16:10:30.827468Z ERROR lact_daemon::server::handler: could not apply settings: Could not write clocks table: io error: Invalid argument (os error 22)

**Comment by ilya-zlobintsev** [comment]
What value are you trying to change?
The DRM warning is most likely unrelated to overclocking settings.

**Comment by nightwolf-1** [comment]
When I change any value in the OC tab, my screen freezes and then turns black.

When I check the logs, there’s only an error related to DRM being too old.

Could this be caused by a program waiting for a response that never arrives, or it arrives but the program can’t understand it due to the version?

**Comment by ilya-zlobintsev** [comment]
The DRM warning only affects fetching information about the GPU, it is not used for overclocking settings.

Could you do the following:
- edit `/etc/lact/config.yaml`, and set `log_level` to `debug` under `daemon`
- restart the service (`sudo systemctl restart lactd`)
- try setting the clocks again
- check the logs - now it should say `writing clocks commands` with info about what specific commands it's using to apply the settings

Also, what is the GPU model?

**Comment by nightwolf-1** [comment]
Yeah sure i can set the debug level to debug  my GPU model is a RX 6900 XT my linux distribution is Arch with 6.6.7-zen1 kernel  if you need i can give you more information

if you want i can give you more log but it's heavy 

[lactd.log](https://github.com/ilya-zlobintsev/LACT/files/13731652/lactd.log)

**Comment by ilya-zlobintsev** [comment]
The logs seem fine. Maybe your GPU doesn't properly handle this low of a max clockspeed? (600 MHz)
You can try setting it manually by writing to the sysfs, and see if you still get the crash:
```
echo 's 1 600' | sudo tee /sys/class/drm/card2/device/pp_od_clk_voltage
echo 'c' | sudo tee /sys/class/drm/card2/device/pp_od_clk_voltage
```

**Comment by nightwolf-1** [comment]
when i trying this it crash but when i put bigger value it crash 

thanks you so much for your help

**Comment by ilya-zlobintsev** [comment]
You mean it doesn't crash when you put a bigger value? Can this issue be closed?

**Comment by nightwolf-1** [comment]
No it always crash but i don't know why
