### ISSUE TITLE
Fan control doesn't work. (7800XT) 

### ISSUE THREAD

**Issue by 32bitx64bit** [ilya-zlobintsev/LACT#235]
Fan control doesn't seem to work. 
I'm on Linux kernel 6.7 RC8

**Comment by 32bitx64bit** [comment]
Driver is Mesa 23.3.2-arch1.2

**Comment by ilya-zlobintsev** [comment]
I'm currently working on adding support for it, as RDNA3 has very different fan settings compared to other generations. Also see #229

**Comment by 32bitx64bit** [comment]
> I'm currently working on adding support for it, as RDNA3 has very different fan settings compared to previous generations. Also see #229

Hopefully it comes sooner rather than later, as I'd prefer my GPU not run at 80C.

**Comment by neon-sunset** [comment]
This is a FOSS project led by a single person which they contribute to in their free time. If you'd like to see this sooner you may want to ask if there are any steps that other contributors can take to help the requested change get implemented.

**Comment by ilya-zlobintsev** [comment]
I've added support for configuring the new settings of the automatic fan curve (target temperature, minimum fan speed and target/limit speed). Support for full-fledged custom fan curves will be added later.

**Comment by 32bitx64bit** [comment]
> I've added support for configuring the new settings of the automatic fan curve (target temperature, minimum fan speed and target/limit speed). Support for full-fledged custom fan curves will be added later.

Cool. I'll give this PR a test run.
Im not a programmer, so I sadly do not have the knowledge to contribute, I would if I could. But I am greatful to see things moving! :D

**Comment by 32bitx64bit** [comment]
Seems the Power usage limit isn't correct for the 7800XT. As its TDP is 263, and can get up to 299 watts in Windows adrenaline if u set the power limit to +15%

**Comment by ilya-zlobintsev** [comment]
Please include a debug snapshot: https://github.com/ilya-zlobintsev/LACT#reporting-issues

**Comment by 32bitx64bit** [comment]
Hm.
![ksnip_tmp_JbrpXi](https://github.com/ilya-zlobintsev/LACT/assets/86190528/3e04eab8-69a0-40ad-92c7-ab9eba02045b)

**Comment by 32bitx64bit** [comment]
Any news on the power limit?

**Comment by ilya-zlobintsev** [comment]
LACT doesn't use values for specific GPU models, the settings and limits are reported by the driver.
The issue with the power limit being lower than it should be is currently being worked on on the kernel side: https://gitlab.freedesktop.org/drm/amd/-/issues/2356
Also see #237

**Comment by 32bitx64bit** [comment]
> LACT doesn't use values for specific GPU models, the settings and limits are reported by the driver. The issue with the power limit being lower than it should be is currently being worked on on the kernel side: https://gitlab.freedesktop.org/drm/amd/-/issues/2356 Also see #237

Ah, ok. Thanks for clearing this up. Hopefully it gets fixed driver side!

**Comment by ilya-zlobintsev** [comment]
As for the original issue with fan control: custom fan curves are now also supported.

**Comment by 32bitx64bit** [comment]
> As for the original issue with fan control: custom fan curves are now also supported.

Nice! I'll give it a run, and close the issue. If anything pops up with it I'll reopen.
