### ISSUE TITLE
Overclocking on Polaris (Linux Mint) is not being enabled

### ISSUE THREAD

**Issue by LyGhT1337** [ilya-zlobintsev/LACT#236]
Hey!

I just installed LACT and tried to enable the OC Feature.. but when trying to do so, the corresponding file is getting created -> I restart the system as prompted but it just sets me back to the "Enable Overclocking" and it won't enable it even though the File was created.

How do I proceed?

**Comment by LyGhT1337** [comment]
Card: RX 570
OS: Linux Mint 21.2 Cinnamon 

Installed lact-0.5.1-0.amd64.ubuntu-2204

**Comment by ilya-zlobintsev** [comment]
Try running `sudo update-initramfs -u`. Then reboot, and check if it works. 
This seems to be caused by #190

**Comment by ilya-zlobintsev** [comment]
This command will now get executed automatically.

**Comment by LyGhT1337** [comment]
fixed it =) Thank you!

**Comment by LyGhT1337** [comment]
Hey!

Sorry for re-opening, found another issue -> I can adjust any setting, but if I touch the memory (Doesn't matter if +1 or -1 on max clock) it will give me artifacts all over the place only fixable through shutting down and restarting.

Core Clock OC works fine without issues

**Comment by ilya-zlobintsev** [comment]
Do you get the same artifacts if you set the memory clock manually, and not through LACT? Try these commands:
```
echo 'm 2 1750 975' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage # Adjust to your vram clockspeed and voltage values, these were taken from an rx 580
echo 'c' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
```
If you still get artifacts, then it's most likely a hardware/firmware issue with the card.

**Comment by LyGhT1337** [comment]
Nah it causes that aswell, odd though as under Windows I can set the Memory up to 2150 without issues

**Comment by ilya-zlobintsev** [comment]
Then it's probably a driver issue - you should report it on https://gitlab.freedesktop.org/drm/amd. In any case, there isn't much that can be done from LACT's side about this.
