### ISSUE TITLE
Wrong power limit on custom 7900 XTX (just making sure this is considered)

### ISSUE THREAD

**Issue by 43615** [ilya-zlobintsev/LACT#237]
I have a Sapphire blah blah 7900 XTX, which comes with a default board power limit of 420 W (increasable by 15% (=483 W) using AMD's software on Windows).
In LACT 0.5.1 with kernel 6.6.9, the slider is capped at 339 W. I'm assuming it's using some fallback value as that doesn't even make sense for AMD's stock cards.
Don't worry, I know that you're still working on RDNA 3 support and that some of it will only be possible with kernel 6.7. Fan control is honestly more of a priority for me, but will power limits also be considered?

**Comment by ilya-zlobintsev** [comment]
The power limit API in RDNA3 is the same as in previous generations, so there shouldn't be any changes required for it on LACT's side. However it looks like there are people reporting a similar issue with the power limit being lower than expected: https://gitlab.freedesktop.org/drm/amd/-/issues/2356

It's also probably worth checking if the issue still persists in kernel 6.7, where the bulk of RDNA3 overdrive support is added. But in either case, this seems to be a kernel-side issue

**Comment by FerrumMaster** [comment]
In kernel 6.7 you can undervolt and set the power limit lower, but not higher, you need to compile your own kernel with a patch.

**Comment by ilya-zlobintsev** [comment]
There have been some updates regarding the power limit setting in kernel 6.7.3:
```
drm/amd/pm: update the power cap setting
drm/amd/pm: Fetch current power limit from FW
```
It's worth checking if that helps with the incorrect limit

_Originally posted by @ilya-zlobintsev in https://github.com/ilya-zlobintsev/LACT/issues/255#issuecomment-1921796576_

**Comment by 43615** [comment]
It changed but is still wrong (goes up to 402 now). Assuming it allows a 15% increase, this suggests an incorrect "default" value of 350 W.

**Comment by ilya-zlobintsev** [comment]
As this is/was a kernel-side problem, i'm going to close this issue. However https://github.com/ilya-zlobintsev/LACT/issues/255 will remain for tracking changes
