### ISSUE TITLE
oc profile 99-amd rule not being created/oc profile question not asked

### ISSUE THREAD

**Issue by robzombie91** [ilya-zlobintsev/LACT#240]
I updated from 0.5.1 to 0.5.2 compiled directly from the git. In overclocking it doesnt have the warning to enable overclocking and the 99 file isnt created in the /etc/modprobe.d folder

Should mention im using Kde plasma 5.27

**Comment by ilya-zlobintsev** [comment]
Was the warning present in the previous version (0.5.1)?

**Comment by ilya-zlobintsev** [comment]
Looking at the snapshot, it seems like you already have overdrive enabled, likely with a boot option.

**Comment by robzombie91** [comment]
Maybe add some code to check if the file exists in /etc/modprobe.d

**Comment by robzombie91** [comment]
Hmm. Well it doesn't do anything. I wont be able to do any more testing until tonight but I tried setting the fan speed and it didn't do anything other than what was automatically set

**Comment by ilya-zlobintsev** [comment]
You should have settings that configure the fan behaviour in the automatic fan control mode (target temperature, minimum speed etc). The custom curve/static speed modes are not currently supported on RDNA3.

**Comment by robzombie91** [comment]
Yeah I set it in there. The fan speed stayed at 0

**Comment by robzombie91** [comment]
ok, confirmed it does go to max but after the gpu gets hot enough

**Comment by ilya-zlobintsev** [comment]
Please check if the issues are resolved when using the latest version

**Comment by ilya-zlobintsev** [comment]
I will close this as the original problem of OC not being available was solved. RDNA3 fan control quirks can be tracked in #255
