### ISSUE TITLE
Setting a custom max voltage/max clock doesn't seem to affect lower power states when it should

### ISSUE THREAD

**Issue by pinbuck** [ilya-zlobintsev/LACT#242]
GPU: rx 580

The problem: Undervolting requires all previous power stages to have the same max voltage and max clock to do its intended goal: reducing noise, thermals, and power consumption

pine@BOXOFDOOM:~$ cat /sys/class/drm/card1/device/pp_od_clk_voltage 
OD_SCLK:
0:        300MHz        750mV
1:        600MHz        769mV
2:        900MHz        918mV
3:       1145MHz       1137mV
4:       1215MHz       1150mV
5:       1257MHz       1150mV
6:       1300MHz       1150mV
7:       1250MHz       1100mV
OD_MCLK:
0:        300MHz        750mV
1:       1000MHz        800mV
2:       2000MHz        950mV
OD_RANGE:
SCLK:     300MHz       2000MHz
MCLK:     300MHz       2250MHz
VDDC:     750mV        1200mV

Steps to reproduce problem: Set core clock, core voltage, and memory clock to less than previous power states' clocks within LACT GUI

The solution: Similar to CoreCtrl or MSI Afterburner, when the user sets a max number, all previous stages should be no higher than that number.

Also, 0xfffd7fff should probably be the right ppfeaturemask to recommend in the readme for AMD gpus, while undervolting/overclocking, it leaves power saving features which 0xfffffff turns off.

![image](https://github.com/ilya-zlobintsev/LACT/assets/96911866/18c1c245-4d7e-46c6-ba71-2a190611ed9c)

**Comment by ilya-zlobintsev** [comment]
You're right, it currently only affects the highest power state. This should be relatively easy to fix.

Regarding the feature mask: when you enable overdrive from LACT with the button, it does apply only what is necessary for overdrive (it takes the current mask and adds overdrive). I suppose the instructions for setting a boot option manually could include this as well.

**Comment by ilya-zlobintsev** [comment]
This has been fixed.

**Comment by pinbuck** [comment]
Thanks, very good project 🫡
