### ISSUE TITLE
Overclocking not working in Ubuntu 22.0.4.3 (Lubuntu)

### ISSUE THREAD

**Issue by odee2004** [ilya-zlobintsev/LACT#243]
Even after clicking "Enable Overclocking" and rebooting, OC does not work.

![image](https://github.com/ilya-zlobintsev/LACT/assets/6821225/8622246a-e4bd-4a2d-854d-c261e07a7a3c)

**Comment by lucaspfl** [comment]
Same problem,
I fixed mine with this steps

sudo nano /etc/default/grub

GRUB_CMDLINE_LINUX_DEFAULT="amdgpu.ppfeaturemask=0xFFF7FFFF"

sudo update-grub
sudo reboot

I don't know if this featuremask change for different gpu cards, but you can take yours in /etc/modprobe.d/99-amdgpu-overdrive.conf

**Comment by ilya-zlobintsev** [comment]
This is the same issue as in #236 , it was fixed in master but not yet in the latest release

**Comment by odee2004** [comment]
@

> Same problem, I fixed mine with this steps
> 
> sudo nano /etc/default/grub
> 
> GRUB_CMDLINE_LINUX_DEFAULT="amdgpu.ppfeaturemask=0xFFF7FFFF"
> 
> sudo update-grub sudo reboot
> 
> I don't know if this featuremask change for different gpu cards, but you can take yours in /etc/modprobe.d/99-amdgpu-overdrive.conf

It's working now. Thanks for your help!

**Comment by lucaspfl** [comment]
glad to help

**Comment by odee2004** [comment]
https://github.com/ilya-zlobintsev/LACT/issues/243#issuecomment-1889466824
