### ISSUE TITLE
VRAM max value for RX 6650 XT

### ISSUE THREAD

**Issue by odee2004** [ilya-zlobintsev/LACT#244]
I have an AMD RX 6650 XT gpu but why is the VRAM Clock only up to 1200 MHz? I think the minimum value is 1900 or something. In windows I can change it around ~2300 MHz.

![image](https://github.com/ilya-zlobintsev/LACT/assets/6821225/5cf01283-9f7b-44de-871f-c6ceebf1af1a)

**Comment by odee2004** [comment]
Oh okay, memory clock has different value in Linux :D

**Comment by ilya-zlobintsev** [comment]
With GDDR6, the effective memory clock is double the actual clockspeed. Windows shows you the effective clock, so basically just multiply it by 2 if you want to set the same values.

**Comment by odee2004** [comment]
Thanks for the info!
