### ISSUE TITLE
Wrong PCI-E Speed and Lanes

### ISSUE THREAD

**Issue by kada49** [ilya-zlobintsev/LACT#247]
My motherboard only supports PCI-E 3.0, My GPU (RX 6650 XT) has PCI-E 4.0, but only connected with 8 lanes. In the App though it shows `16.0 GT/s PCIe x16`. From my understanding 2.0 GT/s per lane is PCIe 4.0, PCIe 3.0 is 1 GT/s per lane. So I think it should show `8.0 GT/s PCIe x8`, because 8 lanes per 1 GT/s. It does not count the motherboard only supporting PCIe 3.0.
Edit: version 0.5.1

**Comment by ilya-zlobintsev** [comment]
What's the output of `grep . /sys/class/drm/card*/device/*_link_*`?

**Comment by Umio-Yasuno** [comment]
This issue should have been fixed with `amdgpu-sysfs-rs v0.12.8`.

https://github.com/ilya-zlobintsev/amdgpu-sysfs-rs/commit/33aba4f9d728cfb97dff0e84ff28d97fa9bb1bd8

**Comment by ilya-zlobintsev** [comment]
Ah yeah, forgot about that, you should try the [latest build from master](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build)

**Comment by kada49** [comment]
I'll try that. Is there a stable release schedule for that fix?

**Comment by ilya-zlobintsev** [comment]
New stable release will be out once all of the RDNA3 functionality is complete.
