### ISSUE TITLE
How can i proper Enable OC 

### ISSUE THREAD

**Issue by ind4skylivey** [ilya-zlobintsev/LACT#253]
i try run as root user and as a normal user and always the same.... it doesn't  ENABLE the OC

**Comment by ilya-zlobintsev** [comment]
I need more info. What is your distro? GPU model? What exactly is happening?

**Comment by ilya-zlobintsev** [comment]
For some reason LACT couldn't detect your distribution info.
You need to run:
```
sudo dracut --regenerate-all --force
```
and then reboot for overclocking to get enabled.
