### ISSUE TITLE
Settings are broken (RDNA3, 0.5.2)

### ISSUE THREAD

**Issue by 43615** [ilya-zlobintsev/LACT#254]
I previously played around with 0.5.1, but RDNA3 wasn't supported. Now I'm trying it again after updating everything, but my settings seem to be broken.
When clicking Apply, it always snaps back to the state it was in when messing with version 0.5.1. This results in being unable to save anything since there's one fan control point too much.
It appears that it's somehow unable to overwrite the settings. Running the GUI as root and reinstalling with a fresh config (`pacman -Rn`) doesn't help. Do you have any ideas? Maybe `chmod` or delete some files manually?

Error popup:
![image](https://github.com/ilya-zlobintsev/LACT/assets/53740368/9c713b27-cfa0-4405-8e3d-37a6dc834fe8)

**Comment by ilya-zlobintsev** [comment]
You probably had a custom fan curve applied back in 0.5.1, which wasn't supported on RDNA3. Now it's trying to apply the curve, and is failing to do so.
You should be able to remove one of the curve points on the thermals page, so the curve becomes valid.
If that doesn't work, you can fully reset the config by removing `/etc/lact/config.yaml` and restarting the service.

**Comment by 43615** [comment]
That worked, thanks!
To clarify, it would always replace the curve with a 6-point one.
