### ISSUE TITLE
Undervolting doesn't work?

### ISSUE THREAD

**Issue by cybbro** [ilya-zlobintsev/LACT#257]
I wanna ask, if undervolting even working on RDNA3 cards? I am on Ubuntu 23.10 / Kernel 6.7.3 / Mesa 23.3.5 Even if I choose to undervolt by 200mV - games and everything works like it should no crashes or anything, no GPU temperature changes... it looks like this feature does nothing.

![image](https://github.com/ilya-zlobintsev/LACT/assets/10908092/b327cb77-e40c-4136-9046-38059c80a250)

![image](https://github.com/ilya-zlobintsev/LACT/assets/10908092/0b8b0e45-7b90-4253-b5df-a4169a8e5616)

**Comment by ilya-zlobintsev** [comment]
Could you include a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues)?

**Comment by cybbro** [comment]
> Could you include a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues)?

Of course! https://drive.google.com/file/d/1hm-HrEGW75q3x8fXP1xbMq-ir6tbaD7C/view?usp=sharing

**Comment by ilya-zlobintsev** [comment]
Everything looks fine - the voltage offset is being applied correctly. Are you sure the measured voltage under load doesn't actually change?
It's also possible that your GPU is being limited by something other than the voltage, like the power limit for example.

**Comment by cybbro** [comment]
> Everything looks fine - the voltage offset is being applied correctly. Are you sure the measured voltage under load doesn't actually change? It's also possible that your GPU is being limited by something other than the voltage, like the power limit for example.

Yes! Indeed it works my apologies. It is a bit different when coming from Windows.
