### ISSUE TITLE
Unable to apply any fan settings on AMD 7900XTX / 6.7.3 kernel / 5.2 LACT

### ISSUE THREAD

**Issue by PoonHarpoon** [ilya-zlobintsev/LACT#258]
When trying to apply any of the fan settings, Curve, Static, Automatic, LACT will Throw an error and will not apply any changes.
![image](https://github.com/ilya-zlobintsev/LACT/assets/52467605/a2a15ff2-c0d2-455c-9bd6-4d13dd2c4448)
This Error will show despite either using a static fan setting or reducing the curve points to <6.

Despite other reports mentioning fan speed reporting not working, mine correctly reports the fan speed whenever the vbios turns the fan on/off. As well the Power limit setting is functional.

System info:
![image](https://github.com/ilya-zlobintsev/LACT/assets/52467605/194f660b-3920-4c5d-bf5a-12e505fced4c)
EndeavorOS (Arch Based) 6.7.3-zen1-2-zen  
My only guess is this may be related to different vendors vbios fan controls and their interaction with LACT.

Before Kernel 6.7.3 and LACT 5.2 I would get the i/o error, now after updating I get this error. I have also passed the boot parameter `amdgpu.ppfeaturemask=0xffffffff` and all other OC controls seem to work. 

I have attached the debug snapshot.
[LACT-sysfs-snapshot-20240205-203111.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/14173640/LACT-sysfs-snapshot-20240205-203111.tar.gz)

**Comment by ilya-zlobintsev** [comment]
This happen when you have tried setting a custom curve in an old version of LACT that didn't handle RDNA3 properly, the curve wasn't applied, but was saved regardless. Now it's trying to apply this old, now incorrect, curve.

The easiest solution is to remove `/etc/lact/config.yaml` and restart the daemon to reset all of the settings.

**Comment by PoonHarpoon** [comment]
Yep, that was the issue. Works perfectly now.
