### ISSUE TITLE
Deb package

### ISSUE THREAD

**Issue by ilya-zlobintsev** [ilya-zlobintsev/LACT#26]
There is a .deb package for LACT now that was created using [this tool](https://github.com/hwittenborn/makedeb), it can be downloaded from the [releases page](https://github.com/ilyazzz/LACT/releases/tag/v0.1). I've tested it on a pop_os VM and it seems to work fine, however I'd like to receive feedback on how it works on other debian-based systems.

**Comment by ilyazzz** [comment]
@SvenMoenig could you try now? I've updated the file in the release.

**Comment by ilyazzz** [comment]
Nevermind, just tried it on a debian VM and it fails because it was linked against a newer version of glibc (included in ubuntu i was building it on).

**Comment by ilya-zlobintsev** [comment]
There are now deb packages generated by pkger as part of a workflow.
