### ISSUE TITLE
RX 7800 XT fan speen dont work

### ISSUE THREAD

**Issue by nux-vom** [ilya-zlobintsev/LACT#263]
Setting up fans on the PX 7800 XT does not work. I install the program from the package and launch the daemon. I add amdgpu.ppfeaturemask=0xffffffff to the GRUB
[LACT-sysfs-snapshot-20240209-120511.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/14219827/LACT-sysfs-snapshot-20240209-120511.tar.gz)

I adjust the curve in the program, but nothing happens. The coolers remain at 0% until 70 degrees, then they start up at full speed, run for 10 seconds and stop.

OS: nobara
kernel:
6.7.0-204.fsync.fc39.x86_64

What am I doing wrong?
Please, help.

**Comment by ilya-zlobintsev** [comment]
RDNA3 GPUs have a cutoff point below which the fan is always off, regardless of curve settings. Unfortunately the driver does not currently provide a way to disable this behaviour.

**Comment by nux-vom** [comment]
Thanks. Are there any options to make the cooler spin at the speed I want?

**Comment by ilya-zlobintsev** [comment]
It uses the configured speed once the GPU reaches a certain temperature (depends on hardware). It's always off below it, there is no way to change that currently, as no setting for it is exposed by the driver.

**Comment by nux-vom** [comment]
understood, thanks!

**Comment by nux-vom** [comment]
understood , thanks!
