### ISSUE TITLE
Allow setting a fan start/stop speed

### ISSUE THREAD

**Issue by oehme** [ilya-zlobintsev/LACT#266]
Right now, if I have a fan curve like

50°C - 0%
60°C - 15%
70°C - 25%

and I'm running a light load (e.g. a 2D game) the graphics card reaches ~55°C and LACT will interpolate between 0% and 15%. This either leads to whining noises, because the fan can't start at lower than ~15%, or it leads to constant start/stop cycles as the temperature hovers around the point where the fan actually starts.

There should be a fan start speed setting. The fan would only start once the curve reaches that speed. If temps drop, the fan will slow down below this start speed (most fans can run below the speed they start at) and will stop once it reaches a certain minimum speed. It will then only start again once it reaches the start speed on the curve again. This way the start/stop cycles would be much longer and the fan would never get a PWM signal that it can't handle.

See a similar feature in [corectrl](https://gitlab.com/corectrl/corectrl/-/wikis/AMD-GPUs#fan-stop-feature) and its [implementation](https://gitlab.com/corectrl/corectrl/-/blob/master/src/core/components/controls/amd/fan/curve/fancurve.cpp?ref_type=heads#L98). They only have a start speed and are missing the stop speed.

In [fancontrol](https://linux.die.net/man/8/fancontrol) these values are called `MINSTART` and `MINSTOP`

**Comment by ilya-zlobintsev** [comment]
Sounds reasonable. This shouldn't be too difficult to implement.

**Comment by ilya-zlobintsev** [comment]
@oehme Could you try building the `feature/fan-threshold` branch and see how it works for you? I've added fan start and stop thresholds, but my GPU doesn't have an audible transition between the fan being on and off, so I cannot test for sure that it works properly.

**Comment by dccoder84** [comment]
I guess this exactly the feature I wanted. I compiled and tried the feature branch "fan-threshold". For now I cannot say if it's working. What do the threshold numbers mean? Are they degree Celcius or percent? What I can tell is that these values are not saved. When I close Lact then my threshold settings are gone.

In my case I have a Radeon RX 6600 and when I watch videos for example on Youtube then the decocing happens on the GPU. By default without any tools like Lact the driver fan handling is a bit nervous going from zero to a bit noisy 1500 rpm when watching videos. With Lact I can lower that to 750 rpm which is silent to my ears. But as stated above the fans are going on and off the whole time. So lets say the fans should turn on at 55 °C with 750 rpm and then should cool down to 50 °C. How should I setup the threshold sliders?

Ah, and one more little thing. Can we have a make clean in the make file?

**Comment by ilya-zlobintsev** [comment]
@dccoder84 
Since this issue was created there was fan control hysteresis implemented in #291 , which lets you set a threshold for how much the temperature needs to change and for how long it needs to stay at a lower value. This can prevent the fan ramping up and down by keeping it at the same speed until the configured conditions are met. It should help in your case, and it's a more universal solution than start/stop thresholds.

However, if it doesn't work for you, and you want to try this branch:
> What do the threshold numbers mean? Are they degree Celcius or percent?

They are in percentages, 0 to 100.

> What I can tell is that these values are not saved. When I close Lact then my threshold settings are gone.

Make sure you're running a version of the daemon built from that branch, otherwise the settings won't get used.

For your setup, you should be able to set the stop threshold at your 55C speed and start threshold at the 50C speed.

> Ah, and one more little thing. Can we have a make clean command in the make file? 😸

You just need to delete the `target` directory. You should only ever need to do this to free up space used up by old builds.

**Comment by oehme** [comment]
Sorry for the delayed response - The machine in question was not mine, but a friends, so I couldn't test for a while. The solution in #291 works fine for them, so this one is no longer needed from my perspective.

**Comment by ilya-zlobintsev** [comment]
I'm going to close this as #291 should prevent the original issue of the fan speed being changed too often in the majority of cases.

**Comment by StarTroop** [comment]
Sorry to resurrect this, but is the fan stop/start threshold feature planned to be officially added? I have a 6600 xt which will not spin down below 31% if I use a custom fan curve (i.e. the fan will only turn off in Automatic mode). The fan start feature in Corectrl works nicely, so I'd like to see it implemented here. Was the aforementioned feature branch not working correctly?

**Comment by dccoder84** [comment]
Right now we have the features "Spindown delay" and "Speed change threshold". It solves the issue of permanently turning on and off of the fans to some degree. Personally I would like to be able to turn on the fans at 55 °C and turn them of at 50 °C. Maybe I could achieve this with the "speed change threshold" but then this would also affect the whole fan curve and not only at the beginning. So I think there is still room for improvement and discussion.

**Comment by StarTroop** [comment]
Yeah, the spindown delay and speed change threshold are good solutions for the issue of unnecessary speed ramping, but for my case of the Fan Stop feature not working in any custom mode, the originally proposed solution would be better (assuming it works like Corectrl). I'm not sure if I should create a new issue, or piggyback on this one. It may also be good to know if my issue is unique, as I would imagine that someone else might have noticed the Fan Stop feature not working if it were common spread. I know the 7XXX series has the issue of **not** being able to circumvent Fan Stop, but I haven't found any discussion about how it works in the 6XXX series.

**Comment by dccoder84** [comment]
So what I tried to say is that while I may be able to turn off fans at 50 °C and turn them on at 55 °C I cannot at the same time set a fine grained speed change for the rest of the fan curve for example change fan speed every 2 °C with the "speed change threshold".
