### ISSUE TITLE
Add ability to change ECC memory setting on W6800 GPU

### ISSUE THREAD

**Issue by ccbadd** [ilya-zlobintsev/LACT#272]
I like to ask that a option be added to enable/disable ECC support for the Radeon Pro W6800 (or any of the other cards that might support it).  The setting is available on the windows driver but all I have been able to find for linux is this site:  [Disable ECC](https://lunnova.dev/articles/amdgpu-disabling-ecc/)

**Comment by ilya-zlobintsev** [comment]
As per the guide, doing this requires building and booting a custom kernel. That is not something that can be handled by LACT, it just talks to the driver. 
You should leave an issue on https://gitlab.freedesktop.org/drm/amd about adding this as a configurable option in the driver.

**Comment by ilya-zlobintsev** [comment]
Closing as this is not possible to implement from within LACT. Could be reopened if the driver adds support for it.
