### ISSUE TITLE
GPU Clock is maxed out when the GUI is running

### ISSUE THREAD

**Issue by Lassebq** [ilya-zlobintsev/LACT#275]
Running LACT GUI makes the GPU increase clock speed up to the last 2 power states (1300-1400MHz) when automatic performance level is set.

In the same  scenario amdgpu_top stays on the first two power states and keeps the clock around 300-400MHz

GPU: Nitro+ Radeon RX 580

**Comment by ilya-zlobintsev** [comment]
Do you mean the GPU clocks up simply because of having the GUI open, even without changing any settings?
That sounds weird, LACT doesn't do anything GPU-heavy, so it shouldn't be different to running any other graphical app.

**Comment by Lassebq** [comment]
Yes, that's exactly what happens. It doesn't matter which tab is open. Power draw also increases from 30-40 to 50-60W

**Comment by ilya-zlobintsev** [comment]
I cannot reproduce this on an Sapphire RX 580 Pulse. The GPU stays in the first power states and the power usage is still around 30-40w. Maybe something in your setup is causing GTK to be more resource-intensive? Does the usage increase when running other GTK (GTK4 specifically?) apps?
![image](https://github.com/ilya-zlobintsev/LACT/assets/22796665/b8f7ec87-7854-46d2-be82-ff16f98369e6)

**Comment by Lassebq** [comment]
Which display server (and if Wayland, mention the compositor) and which gtk backend are you using?
I will make tests under the same conditions.

**Comment by ilya-zlobintsev** [comment]
I checked on both Wayland and X11 on a KDE session. GTK is using its default OpenGL backend. The GTK version is 4.12.5.

**Comment by Lassebq** [comment]
Any redraw in GTK 4 apps bumps up clock and increases GPU usage to the last two power states **on X11** (and seemingly other wayland compositors that are not GNOME?). No screen updates keeps it down.
However, it is using significantly less power with either backend on the GNOME Wayland side.
Tested on GTK 4.12.5 and 4.13.8

**Comment by Lassebq** [comment]
Also, it seems that LACT is no longer affected by high GPU usage. So it was most definitely related to GTK and/or Wayland compositor in use.
