### ISSUE TITLE
Wrong GPU Model in Hardware Information

### ISSUE THREAD

**Issue by RandomLegend** [ilya-zlobintsev/LACT#285]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

[LACT-sysfs-snapshot-20240308-175020.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/14540924/LACT-sysfs-snapshot-20240308-175020.tar.gz)

As you can see in the screenshot:
![image](https://github.com/ilya-zlobintsev/LACT/assets/38812603/c4540b9e-c4a9-4dca-997e-3e727501ba6a)

It shows i have a RX 7900 XTX in hardware info, but vulkan recognizes it correctly. In the bottom you can see amdgpu_top also showing the correct card.

Just an fyi.

### System info

```markdown
- LACT version: 0.5.3-release (commit d99cfdf)
- GPU model: Sapphire Pulse RX 7900 XT
- Kernel version: 6.7.8-zen1-1-zen
- Distribution: Garuda-Linux
```

**Comment by ilya-zlobintsev** [comment]
The GPU model that you see being reported by the vulkan driver and amdgpu_top is the model of the GPU itself. You can also see it in LACT in the top left selector (though it's less specific and shows both XT and XTX, as it uses the PCI device id rather than information from the driver).

The model listed in "GPU model" is the name of the card from the board manufacturer, in this case Sapphire. They list this id as being a 7900 XTX in the PCI database: `1da2 471e  PULSE RX 7900 XTX`. This is normal and common for sibling cards that use the same chip. However, I agree that this is confusing, and perhaps there could be a more clear separation in the info display for GPU model vs card model.

**Comment by ilya-zlobintsev** [comment]
This should now be more clear, for example: ![image](https://github.com/ilya-zlobintsev/LACT/assets/22796665/c59bc081-268c-44f0-a099-e837328811e2)

**Comment by Umio-Yasuno** [comment]
`libdrm_amdgpu` determines the model name using the device ID and revision ID.  

https://gitlab.freedesktop.org/mesa/drm/-/blob/main/data/amdgpu.ids?ref_type=heads

I suggest displaying the revision ID or getting the model name in 
[libdrm_amdgpu_sys::AMDGPU::DeviceHandle::get_marketing_name](https://docs.rs/libdrm_amdgpu_sys/0.6.0/libdrm_amdgpu_sys/AMDGPU/struct.DeviceHandle.html#method.get_marketing_name)
or 
[libdrm_amdgpu_sys::AMDGPU::GPU_INFO::find_device_name](https://docs.rs/libdrm_amdgpu_sys/0.6.0/libdrm_amdgpu_sys/AMDGPU/trait.GPU_INFO.html#method.find_device_name) .

**Comment by ilya-zlobintsev** [comment]
Using drm for this would allow for a more specific GPU model since it takes the revision into account (unlike the pci.ids file). However the original issue is regarding the card model from the board vendor (pci subsystem id), which as far as I know drm doesn't have any information about.

**Comment by Umio-Yasuno** [comment]
> However the original issue is regarding the card model from the board vendor (pci subsystem id), which as far as I know drm doesn't have any information about.

I think the PCI database needs to be updated to resolve it.  
Also, the PCI database does not take the revision ID into account, so we should only get names like "RX 7900 XT/XTX" instead of "RX 7900 XT".  

https://admin.pci-ids.ucw.cz/read/PC/1002/744c

**Comment by ilya-zlobintsev** [comment]
The DRM name will now be used when possible for the GPU model. This will be more accurate, and should show the exact model in most cases.
I don't think there's anything else that can be done about name identification, so I'm going to close this.
