### ISSUE TITLE
Restart/reload if config file changed

### ISSUE THREAD

**Issue by Atemu** [ilya-zlobintsev/LACT#290]
When you edit the config file by hand or through other means, you must manually restart the daemon. It'd be great if the deamon could watch the file and read in the config again when it's changed.

**Comment by ilya-zlobintsev** [comment]
Implemented in https://github.com/ilya-zlobintsev/LACT/commit/16c50970f6efd200f6f75bb8352c6d050919b786

**Comment by Atemu** [comment]
Thanks!
