### ISSUE TITLE
"Performance Levels" options are not working if "Clockspeeds and Voltages" are set different than default values

### ISSUE THREAD

**Issue by Cruslan** [ilya-zlobintsev/LACT#294]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

If clock speeds and voltages are set different than GPU's current values, GPU ignores "Highest Clocks" and "Lowest Clocks" settings in "Performance Levels", GPU behaves like "Auto" mode. 

When clock speeds and voltages are in default value, GPU behaves whether you set. If you set "Lowest Clock" GPU stays lowest states as possible in under load and performance is reduced as expected. Also if you set "Highest Clocks" GPU reaches highest possible states in under load and performance is higher, also GPU stays maximum clock at idling as expected.

But if user changes any value different than default values, GPU don't apply those settings, GPU behaves like "Auto" option selected whether "Performance Levels" set to "Highest Clocks" or "Lowest Clocks" option. Whether option is set GPU increases its clocks when under load, GPU lowers when idle. 

Those issue only applies "Highest Clocks" and "Lowest Clocks" options. Other options in "Manual" mode seems working as expected. 

### System info

```markdown
- LACT version:5.2 with QT 
- GPU model: Sapphire Pulse labeled AMD Radeon RX 6700 XT
- Kernel version: 6.8.1-x86_64
- Distribution: Gentoo
```

**Comment by ilya-zlobintsev** [comment]
Fixed in https://github.com/ilya-zlobintsev/LACT/commit/d9553a91a18b064060ede88f9e4e69d0e24ecb5f, tested on a 6900 XT
