### ISSUE TITLE
Fan Control Buttons Greyed Out - RDNA3 7800 XT

### ISSUE THREAD

**Issue by andar1an** [ilya-zlobintsev/LACT#295]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

I have looked at the other issues, and I don't see something related to greyed out fan control for RDNA3. 

I just found this today, so if I missed something I can close. Some direction would be great in that case please.

![image](https://github.com/ilya-zlobintsev/LACT/assets/12686470/6826a443-5287-4b08-a4e4-c5547def3c41)
![image](https://github.com/ilya-zlobintsev/LACT/assets/12686470/bb903a50-9fac-40f3-b491-1a13ffa4844d)
![image](https://github.com/ilya-zlobintsev/LACT/assets/12686470/76bd0067-6f3d-429a-a6df-3c891e939d14)

### System info

```markdown
- LACT version: 0.5.3
- GPU model: 7800XT
- Kernel version: 6.7.9
- Distribution: Debian 12
```

**Comment by ilya-zlobintsev** [comment]
There's a warning at the top that you need to enable overclocking support to use fan control. You can do it in the OC page.
![image](https://github.com/ilya-zlobintsev/LACT/assets/22796665/334a696e-ec72-44a1-9252-e6ea6bb3c27f)

**Comment by andar1an** [comment]
Oops, I missed that. Thank you @ilya-zlobintsev, this is very cool.

**Comment by ilya-zlobintsev** [comment]
Is the fan actually spinning? It's possible that it's not spinning, even with this custom curve, see the [note in readme](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) for RDNA3

It's also possible that the speed just isn't being reported correctly by the driver. Other people have had similar behaviour in #255.

**Comment by ilya-zlobintsev** [comment]
It needs to be implemented on the kernel side, most likely by someone from AMD. I don't know if they're planning to do it or not.

**Comment by andar1an** [comment]
Hopefully that happens. They only support commercialized linux distros with their drivers at the moment which is frustrating.
