### ISSUE TITLE
Can't start daemon on Gentoo.

### ISSUE THREAD

**Issue by justas2006** [ilya-zlobintsev/LACT#296]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

"rc-update add lactd default" works fine, but when i try to start it with "rc-service lactd start" it says "rc-service: No such file or directory".
[LACT-sysfs-snapshot-20240329-180843.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/14806176/LACT-sysfs-snapshot-20240329-180843.tar.gz)

### System info

```markdown
- LACT version:5.13
- GPU model:6700xt
- Kernel version:6.6.21
- Distribution:Gentoo
```

**Comment by ilya-zlobintsev** [comment]
Does the daemon work if you run it manually with `lact daemon` (as root)?

I haven't used non-systemd distros, so I'm not too familiar with how the units are installed, you might be better of asking the distro package maintainers about this.

**Comment by justas2006** [comment]
> Does the daemon work if you run it manually with `lact daemon` (as root)?
> 
> I haven't used non-systemd distros, so I'm not too familiar with how the units are installed, you might be better of asking the distro package maintainers about this.

Yeah it actually works. The output i get is "lact_daemon::socket: listening on "/var/run/lactd.sock" "

**Comment by justas2006** [comment]
Solved by doing a system link "ln -s /sbin/openrc-run /usr/bin/openrc-run".

**Comment by Username404-59** [comment]
> I haven't used non-systemd distros, so I'm not too familiar with how the units are installed, you might be better of asking the distro package maintainers about this.

This is because on the "split-usr" gentoo profiles /sbin is a separate directory whereas on the merged-usr ones and on other distributions /sbin and /usr/sbin both point to /usr/bin
