### ISSUE TITLE
About Sea Islands and Southern Islands

### ISSUE THREAD

**Issue by mezka** [ilya-zlobintsev/LACT#299]
I tried all the linux programs available for manual overclocking of these GPUs.

radeon-profile
tuxclocker
corectl

And none works.

Is there something missing or broken with the underlying kernel driver that blocks every gpu clocking application from achieving this feature?

Should we try contacting a DRM kernel dev?

**Comment by ilya-zlobintsev** [comment]
The oldest models that have any kind of overclocking functionality in the kernel are Tonga/Fiji from Volcanic Islands (GCN 3). Earlier cards don't support it, and they don't even use the same driver by default. You might be able to disable some of the built-in power states, but that's about it.

> Should we try contacting a DRM kernel dev?

I doubt AMD will be interested in implementing it, as the GPUs are 10+ years old and typically don't receive any driver updates, let alone major new features.
