### ISSUE TITLE
Resizeable bar reporting

### ISSUE THREAD

**Issue by daevad** [ilya-zlobintsev/LACT#306]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Motherboard bios says that resizable bar is Enabled, CPU-X also indicates Enabled.  LACT says Disabled.

### System info

```markdown
- LACT version: 0.5.4-release (commit 6dc3520)
- GPU model: AMD RX6800
- Kernel version: 6.8.0-76060800daily20240311-generic
- Distribution: Pop!_OS 22.04 LTS

motherboard - Micro-Star International Co., Ltd. MS-7D53  MPG X570S EDGE MAX WIFI
```

**Comment by ilya-zlobintsev** [comment]
At first, I thought that I managed to reproduce this, however, after more investigation it looks like that (at least in my case) resizable bar wasn't actually working (despite being enabled in uefi), and CPU-X was falsely reporting it as enabled.

You can check this with `sudo dmesg | grep -i bar`, it should output something like
```
[5.706574] [drm] Detected VRAM RAM=8176M, BAR=8192M
```
If the BAR value is 256M, then rebar isn't working.

What fixed this for me was disabling CSM/legacy boot in UEFI settings. After this rebar got enabled.

Please check that you aren't experiencing the same situation.

**Comment by ilya-zlobintsev** [comment]
@daevad any updates on this?
