### ISSUE TITLE
constant reporting of throttling while at, essentially,. idle

### ISSUE THREAD

**Issue by Thorazin** [ilya-zlobintsev/LACT#307]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Every few seconds the OC screen in LACT reports my card, a Powercolor Red Devil 7900XTX, as throttling when it is essentially idling, as in  just web browsing or basic computer use. During this time the fans are at zero because temps are not high enough to cause them to activate. LACT is reporting temps currently as  Edge: 35C,Junction: 39C, Mem: 52C and fans at zero rpm. I have attached a photo, including the new historical data charts which is a great idea by the way, and a debug snapshot.

![Screenshot from 2024-04-22 16-10-25](https://github.com/ilya-zlobintsev/LACT/assets/36058075/d8c29d1a-47c5-49e7-ab35-3ab6f10c6633)

[LACT-sysfs-snapshot-20240422-161211.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/15068674/LACT-sysfs-snapshot-20240422-161211.tar.gz)

### System info

```markdown
- LACT version: 0.5.4-release (commit 6dc3520)
- GPU model: Powercolor Red Devil 7900XTX
- Kernel version: 6.8.0-22-generic
- Distribution: Ubuntu 24.04 and 22.04
```

**Comment by Umio-Yasuno** [comment]
https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs/issues/7  
https://gitlab.freedesktop.org/drm/amd/-/issues/3251

**Comment by Thorazin** [comment]
Alright, I am not sure how I missed that, thank you.

**Comment by ilya-zlobintsev** [comment]
Yeah, this is a driver issue, can't do much about it from the application side

**Comment by Roshak** [comment]
Since [This issue](https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs/issues/7) got closed it is something that can be implemented in LACT?

**Comment by ilya-zlobintsev** [comment]
Thanks! I will update LACT to use this soon.

**Comment by ilya-zlobintsev** [comment]
Added in https://github.com/ilya-zlobintsev/LACT/commit/070ea44c47ffac18d93878e5cbc39fbf4266fa6e
