### ISSUE TITLE
[feature request] Provides DEB, RPM packages for ppc64le architecture

### ISSUE THREAD

**Issue by runlevel5** [ilya-zlobintsev/LACT#308]
As title

**Comment by ilya-zlobintsev** [comment]
Could you please explain your use case for this? Are there any PowerPC systems that run AMD GPUs?

**Comment by runlevel5** [comment]
> Could you please explain your use case for this? Are there any PowerPC systems that run AMD GPUs?

Yes many infact. For example the Raptor Computing Talos II or Blackbird could run AMD GPUs for many usecases. For me personally I use my Blackbird workstation like a personal computer, I could play games (like Xonotic, Quake II, Quake III and many more games).

**Comment by ilya-zlobintsev** [comment]
Interesting, I assumed that outside of x86 only ARM has boards capable of running standard desktop GPUs.
I'll take a look at it, but I'm not sure how well the current package build system is fit for cross-compiling, and if there are cross-compilation toolchains readily available in all the target distros.

In the meantime, you should be able to build from source.

**Comment by runlevel5** [comment]
@ilya-zlobintsev let's get the app compiled first https://github.com/ilya-zlobintsev/LACT/issues/309

**Comment by ilya-zlobintsev** [comment]
Pre-built packages are not going to happen as Github does not provide powerpc runners, and cross-compiling is problematic due to dependencies on system packages (gtk, libdrm).

Users of nonstandard architectures can compile LACT from source.

**Comment by ilya-zlobintsev** [comment]
@runlevel5 for Fedora there is now a Copr repository, and it has ppc64le builds: https://copr.fedorainfracloud.org/coprs/ilyaz/LACT/

**Comment by runlevel5** [comment]
@ilya-zlobintsev it does not unfortunately

**Comment by ilya-zlobintsev** [comment]
What do you mean? Here's the current latest one: https://download.copr.fedorainfracloud.org/results/ilyaz/LACT/fedora-41-ppc64le/08262668-lact/
