### ISSUE TITLE
RDNA2 6850M XT: cannot set any profile besides default, power limit has lowered

### ISSUE THREAD

**Issue by trgeiger** [ilya-zlobintsev/LACT#312]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

[LACT-sysfs-snapshot-20240423-203712.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/15084990/LACT-sysfs-snapshot-20240423-203712.tar.gz)

Sometime recently in the last couple weeks LACT has no longer functioned properly for me.

Attempting to set any Manual power level mode just sets it back to BOOTUP_DEFAULT and the power usage limit, which used to go to 150, is now capped at 140. 

I can manually change the power profile modes with something like `echo manual | sudo tee /sys/class/drm/card*/device/power_dpm_force_performance_level && echo 1 | sudo tee /sys/class/drm/card*/device/pp_power_profile_mode` but the LACT GUI is unable to do the same. I am not able to manually set the power limit higher than 140, however.

```cat /sys/module/amdgpu/parameters/ppfeaturemask 
0xffffffff
```

### System info

```markdown
- LACT version: 0.5.4-release (commit 6dc3520) 
- GPU model: 6850M XT
- Kernel version: 6.8.7-301.fsync.fc40.x86_64
- Distribution: Fedora Linux 40
```

**Comment by trgeiger** [comment]
Setting profile works on the previous version of LACT, 0.5.3

**Comment by ilya-zlobintsev** [comment]
> the power usage limit, which used to go to 150, is now capped at 140

This is likely a change in the driver - it was recently updated to follow the VBIOS specified minimum power limit, perhaps something changed about the upper limit too? 140 is indeed what is reported as the max limit in the driver in `/sys/class/drm/card1/hwmon/hwmon5/power1_cap_max` in the snapshot.

Regarding the power profile - should be fixed with https://github.com/ilya-zlobintsev/LACT/commit/0dce4b395efff670fcc14b1cad515aad2392a28c

**Comment by ilya-zlobintsev** [comment]
@trgeiger any update on the power profile? You can try the [test build](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build) from the latest commit.

**Comment by trgeiger** [comment]
The latest test build does let me set power profiles and adjust the power limit, albeit with that new limit of 140. Thanks!
