### ISSUE TITLE
Packages formats

### ISSUE THREAD

**Issue by rafaelnascimentodevs** [ilya-zlobintsev/LACT#315]
A suggestion for improvement would be to implement support for universal packaging formats, such as AppImage or Flatpak. This would streamline the installation and usage of LACT across different Linux distributions, eliminating the need to search for specific packages for each system. Additionally, it would provide a more consistent experience for users, regardless of the distribution they are using.

**Comment by ilya-zlobintsev** [comment]
I've tried. This is already covered here: https://github.com/ilya-zlobintsev/LACT/blob/master/pkg/README.md

**Comment by ilya-zlobintsev** [comment]
Closing as this is currently not feasible
