### ISSUE TITLE
Power level mode always returns to “BOOTUP_DEFAULT”.

### ISSUE THREAD

**Issue by jrieucros** [ilya-zlobintsev/LACT#319]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

[LACT-sysfs-snapshot-20240504-175943.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/15210237/LACT-sysfs-snapshot-20240504-175943.tar.gz)

If I try to change the “Power level mode” to anything other than “BOOTUP_DEFAULT”, it reverts to “BOOTUP_DEFAULT”.

For example, I choose “3D_FULL_SCREEN”, click on Apply and when a popup asks me if I want to keep these new settings, I see that “3D_FULL_SCREEN” has already been changed back to “BOOTUP_DEFAULT”.
No problem with “Performance level”, which remains set to “Manual”.
If I apply the change manually (echo 1 > /sys/class/drm/card5/device/pp_power_profile_mode) and I relaunch LACT, I can see the Power level mode set to “3D_FULL_SCREEN”. But as soon as I change it in LACT, it returns to “BOOTUP_DEFAULT”.
So my current workaround is to run the following command every time I log on:
“echo 1 > /sys/class/drm/card5/device/pp_power_profile_mode”

### System info

```markdown
- LACT version: 0.5.4
- GPU model: AMD RDNA2 6900XT
- Kernel version: 6.8.7-303.fsync.fc40.x86_64
- Distribution: Bazzite 3.0.1
```

**Comment by jrieucros** [comment]
I have my answer in the Issue 312.
So this one is a duplicate, sorry.

**Comment by Atemu** [comment]
Since that thread contains a bunch of discussion about other things, here's the commit which fixed this issue: https://github.com/ilya-zlobintsev/LACT/commit/0dce4b395efff670fcc14b1cad515aad2392a28c

**Comment by Whayme** [comment]
This still occurs with current lact-git, please reopen.

**Comment by Whayme** [comment]
I mentioned it there but as this is a more directly related issue, I'm also posting here that it still occurs on current lact-git.
