### ISSUE TITLE
Is my gpu supported?

### ISSUE THREAD

**Issue by shahriar0247** [ilya-zlobintsev/LACT#322]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation

- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration
[LACT-sysfs-snapshot-20240508-065836.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/15247868/LACT-sysfs-snapshot-20240508-065836.tar.gz)

### Bug description

I just want quick response. Why am i not getting any controls for GPU frequency and temperature on my RS 6700s.
![20240508_064303](https://github.com/ilya-zlobintsev/LACT/assets/47810596/dcad082a-a9e9-46f0-a2d7-2f8a141bd94e)

### System info

```markdown
- LACT version:0.5.4-release (commit 6dc3520)
- GPU model: RX 6700s
- Kernel version: 6.8.8-300.fc40.x86_64
- Distribution: Fedora Linux 40 (Workstation Edition) x86_64 
- Host: ROG Zephyrus G14 GA402RJ_GA402RJ 1.0
```

**Comment by ilya-zlobintsev** [comment]
The GPU doesn't expose proper clocks or voltage control.
`/sys/class/drm/card1/device/pp_od_clk_voltage` doesn't contain values that it normally has:
```
OD_VDDGFX_OFFSET:
0mV
OD_RANGE:
```
So it appears to be unsupported by the kernel.
