### ISSUE TITLE
Add the ability to define power profile mode for indivdual applications.

### ISSUE THREAD

**Issue by Anakin1773** [ilya-zlobintsev/LACT#325]
Hello. I've got a suggestion for the developers of LACT. I've noticed that my AMD GPU (6500 XT) stutters due to the default power mode being too eager to downclock for low GPU load games like Skyrim SE, Black Mesa, etc. In CoreCTRL, you can set the power profile mode per application to something like "3D Fullscreen" or "Compute" to rectify this issue. So my question is this: Will you ever consider adding an option for the user to define what power mode a particular application should use?

Nonethless, I thank the development team of this software, and wish them all a good day.

**Comment by ilya-zlobintsev** [comment]
#251

**Comment by Anakin1773** [comment]
> #251

Ok then, thank you informing me that this was a duplicate.

**Comment by ilya-zlobintsev** [comment]
Implemented in #424
