### ISSUE TITLE
Custom power profile

### ISSUE THREAD

**Issue by Atemu** [ilya-zlobintsev/LACT#328]
It is possible to build your own power profile in `/sys/class/drm/card0/device/pp_power_profile_mode` by using profile 6 ("CUSTOM").

Researching what these values do and setting them as some ordered string like `'6 0 0 5 1 0 4 500 4587520 -65536 0'` is not a great experience; a GUI like LACT could really shine here with labels, sliders and info hovers.

**Comment by ilya-zlobintsev** [comment]
The format of this file is different between generations, which makes it a bit annoying to parse (currently it does not parse the values themselves), but it should be doable. I'll take a look at it.
