### ISSUE TITLE
investigate regarding drm/amd issue 3131

### ISSUE THREAD

**Issue by andrew-ld** [ilya-zlobintsev/LACT#329]
hi, I am the author of the issue https://gitlab.freedesktop.org/drm/amd/-/issues/3131, I think lact developers should be aware of this issue, especially the last comments.

https://gitlab.freedesktop.org/drm/amd/-/issues/3131#note_2415553

**Comment by ilya-zlobintsev** [comment]
Interesting - there have already been issues with the order in which settings are applied, but lact should handle what's described in the issue fine. The current order for apply settings is:
- Power cap
- Clocks table
- Performance level
- Fan curve

Code that handles this: https://github.com/ilya-zlobintsev/LACT/blob/master/lact-daemon/src/server/gpu_controller/mod.rs#L719
Did you manage to hit the issue when applying the settings in lact, or are you just informing about its existence?

**Comment by andrew-ld** [comment]
I opened this issue to keep track of the status of things, however actually even I can't change the fan speed on my sapphire 7900xtx.

for example, I've tried firing the fans to full on the curve and also with static speed and nothing seems to happen.

**Comment by ilya-zlobintsev** [comment]
Is this the case only when you set the fan speed using lact, or when manually writing to the sysfs (like the examples in the linked issue) as well?

**Comment by andrew-ld** [comment]
lact

**Comment by ilya-zlobintsev** [comment]
Makes sense, we can at least avoid writing to the files if the value is unchanged.

**Comment by ilya-zlobintsev** [comment]
@zenofile i've added checks for this in https://github.com/ilya-zlobintsev/LACT/commit/ca3e54015a39f7cc0c840643def5e642ef8ef101, could you test if it helps?

**Comment by ilya-zlobintsev** [comment]
Interesting. Currently the values are committed right away, i'll see if i can make it deferred until everything is written

**Comment by ilya-zlobintsev** [comment]
@zenofile i've pushed the new logic where everything is committed at once to the `deferred-commit` branch, could you test if it works?

**Comment by ilya-zlobintsev** [comment]
I've pushed a commit to reset the fan curve after writing other pmfw values, please tell me if it helps.
And thanks for the detailed debug - it's unfortunate that this is so fragile.

**Comment by ilya-zlobintsev** [comment]
Good to know, I will merge these changes then.

**Comment by ilya-zlobintsev** [comment]
@andrew-ld could you check if this also solves the problem for you?

**Comment by ilya-zlobintsev** [comment]
Closing as this has been implemented and released.
