### ISSUE TITLE
Power control does not remain set when pressing "esc" in Helldivers 2 on 7000 series (RDNA3)

### ISSUE THREAD

**Issue by 32bitx64bit** [ilya-zlobintsev/LACT#330]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

This bug report on CoreCtrl does this solid 
https://gitlab.com/corectrl/corectrl/-/issues/441

Issue is power limit does not remain, and gets reset back to the default when pressing esc in Helldivers 2.
This issue also has different triggers in other games, was able to reproduce in Cities 2, and HD2.

I don't know if its just how both CoreCtrl and LACT how they set the power limit, or if its a underlying driver issue within Mesa.

### System info

```markdown
- LACT version:5.4
- GPU model: 7800XT
- Kernel version: 6.9
- Distribution: Garuda Linx
```

**Comment by Umio-Yasuno** [comment]
The behaviour is probably due to the workaround of the RADV driver.  
Please try setting `radv_force_pstate_peak_gfx11_dgpu=false` as environmental variable.  


https://gitlab.freedesktop.org/mesa/mesa/-/issues/11046#note_2381270

**Comment by 32bitx64bit** [comment]
> The behaviour is probably due to the workaround of the RADV driver. Please try setting `radv_force_pstate_peak_gfx11_dgpu=false` as environmental variable.
> 
> https://gitlab.freedesktop.org/mesa/mesa/-/issues/11046#note_2381270

Hey I've never done enviornmental varibles before, where would I paste this exactly? I'm probably just stupid, just want to make sure.
