### ISSUE TITLE
Wrong pcie link reported

### ISSUE THREAD

**Issue by UnknownSuperficialNight** [ilya-zlobintsev/LACT#334]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

LACT is reporting 

Link Speed: `8.0 GT/s PCIe x16`

while this reports otherwise

`grep . /sys/class/drm/card*/device/*_link_*`:
```
/sys/class/drm/card0/device/current_link_speed:16.0 GT/s PCIe
/sys/class/drm/card0/device/current_link_width:16
/sys/class/drm/card0/device/max_link_speed:16.0 GT/s PCIe
/sys/class/drm/card0/device/max_link_width:16
```

and `sudo lspci -s 0c:00.0 -vvv` returns
```
LnkSta: Speed 16GT/s, Width x16
LnkCap2: Supported Link Speeds: 2.5-16GT/s, Crosslink- Retimer+ 2Retimers+ DRS-
                LnkCtl2: Target Link Speed: 16GT/s, EnterCompliance- SpeedDis-
``` 

### System info

```markdown
- LACT version: 0.5.4-release (commit VERGEN_IDEMPOTENT_OUTPUT)
- GPU model: 7800xt
- Kernel version: linux-6.8.9-gentoo
- Distribution: Gentoo/Linux x86_64
```

**Comment by ilya-zlobintsev** [comment]
On RDNA GPUs the correct link speed isn't shown on the GPU device itself, but on a separate "upstream" PCI device: https://gitlab.freedesktop.org/drm/amd/-/issues/1967#note_1347631

**Comment by ilya-zlobintsev** [comment]
Closing as this is correct behaviour
