### ISSUE TITLE
Adding fan speed to histogram

### ISSUE THREAD

**Issue by melroy89** [ilya-zlobintsev/LACT#335]
What about adding the fan speed over time to the historical data window as well?

Maybe in percentage and in RPM (thus 2 lines) within the same graph? Percentage on the left y-axis, and RPM on the right y-axis.

**Comment by ilya-zlobintsev** [comment]
Implemented in #338 
![image](https://github.com/ilya-zlobintsev/LACT/assets/22796665/ffbc781d-ae04-4bc9-a0c7-428d982a6cb1)

**Comment by melroy89** [comment]
Wow! Cool!
