### ISSUE TITLE
Could not connect to daemon, running in embedded mode.

### ISSUE THREAD

**Issue by SneakiestDuke68** [ilya-zlobintsev/LACT#336]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Hello i have a problem with app, everytime when i run this always get error about permision, error 13. I wrote command "sudo systemctl enable --now lactd" but still get error.
![lact](https://github.com/ilya-zlobintsev/LACT/assets/171153200/0a784cc3-dd3f-446d-8ceb-1acff261b80a)

### System info

```markdown
- LACT version:0.5.4-release-embedded (commit 6dc3520) , 0.5.4-release (commit 6dc3520)
- GPU model:AMD Radeon RX 6800 XT (0x1002:0x73BF:0xC1)
- Kernel version:6.9.1-1-default
- Distribution:OpenSUSE Tumbleweed KDE Plasma
```

**Comment by SneakiestDuke68** [comment]
Ok, i was fix that. I didn't see configuration tab on main page of app, so is need to do this:
"To fix socket permissions in such configurations, edit /etc/lact/config.yaml and add your username or group as the first entry in admin_groups under daemon, and restart the service (sudo systemctl restart lactd)."

**Comment by ilya-zlobintsev** [comment]
As stated in the readme, the default user configuration on OpenSUSE makes it so the user has to be specified manually.
> Same for me with LACT 0.5.5 in Pop!_OS (Kernel 6.8.0) with a RX 7900 GRE.

Check if the daemon is running (`sudo systemctl status lactd`) and if the permissions on the socket are right (`ls -l /run/lactd.sock`)

**Comment by poplar-at-twilight** [comment]
> "To fix socket permissions in such configurations, edit /etc/lact/config.yaml and add your username or group as the first entry in admin_groups under daemon, and restart the service (sudo systemctl restart lactd)."

It works!

I'm also an openSUSE tumbleweed user, and the latest version (v0.5.6) of LACT still requires editing the `/etc/lact/config.yaml` file to manually specify the user group in order for LACT to connect to the daemon.

like this:

```
(lact:7196): Gtk-WARNING **: 08:28:39.875: Unknown key gtk-modules in /home/poplar/.config/gtk-4.0/settings.ini
2024-09-23T00:28:39.972051Z  INFO lact_client::connection::unix: connecting to service at "/var/run/lactd.sock"
2024-09-23T00:28:39.972084Z  INFO lact_gui::app: could not connect to socket: 权限不够 (os error 13)
2024-09-23T00:28:39.972098Z  INFO lact_gui::app: using a local daemon
2024-09-23T00:28:39.993994Z  INFO lact_daemon::server::handler: initialized 2 GPUs
```

Modified configuration file:

```shell
poplar@c004-h1:~> id; echo;cat /etc/lact/config.yaml
uid=1000(poplar) gid=1000(poplar) 组=1000(poplar),108(libvirt),476(flatpak)

daemon:
  log_level: info
  admin_groups:
  - poplar
  - wheel
  - sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
```
