### ISSUE TITLE
Clockspeed / voltages are set but not applied. (7900XTX)

### ISSUE THREAD

**Issue by geludwig** [ilya-zlobintsev/LACT#337]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Clockspeeds or voltages are not applied despite set in GUI (and checked in config files). Kernel parameter `amdgpu.ppfeaturemask=0xffffffff` is also set in systemd-boot. Unsure if I missed something here.

Despite this, power limit is applied correctly up to 350W. Over 350W I use this shell script to bypass the known limitation:
```
#! /bin/bash
sudo su <<EOF
echo 402000000 > /sys/class/drm/card1/device/hwmon/hwmon1/power1_cap
```

In the following example I tried to lower the clockspeeds to 2000MHz, but the sliders dont have any effect (neither clockspeed or voltage).

![clocks_not_working](https://github.com/ilya-zlobintsev/LACT/assets/74719181/94fe9d4c-4395-4605-97ca-160ff6d4b402)

![clock_fix_not_working](https://github.com/ilya-zlobintsev/LACT/assets/74719181/d20faa8e-a471-40a2-9c45-c1a0eaa21839)

[LACT-sysfs-snapshot-20240529-213154.tar.gz](https://github.com/ilya-zlobintsev/LACT/files/15490068/LACT-sysfs-snapshot-20240529-213154.tar.gz)

### System info

```markdown
- LACT version: 0.5.4-release (commit 6dc3520)
- GPU model: XFX SPEEDSTER MERC 310 AMD Radeon RX 7900 XTX Black Edition
- Kernel version: 6.8.0-76060800daily20240311-generic
- Distribution: Pop!_OS 22.04 LTS
```

**Comment by geludwig** [comment]
Tested some more and it seems you can not change clockspeeds and voltages AND also raise the power limit. For the moment you have to decide for one or the other. At least there are no "driver timeouts" like in Windows.

**Comment by ilya-zlobintsev** [comment]
Does it work together with lowering the power limit? I want to know if it's an issue with how settings are applied, or just with how the GPU interprets them.

**Comment by geludwig** [comment]
It is only a problem if the power limit is raised above the official (?) power limit of around 350W.

In the following example I set the clockspeed to 2000MHz. The power limit in the config is set to 402W, but the real power limit is 350W. After that, I set the clockspeed to 3000MHz and the power limit hits 350W, despite being set to 402W in the config.

I could raise the power limit to the real 402W by `echo 402000000 > /sys/class/drm/card1/device/hwmon/hwmon1/power1_cap` as `sudo su`, but the clockspeed and voltage settings would then be ignored.

![Screenshot from 2024-06-01 00-15-00](https://github.com/ilya-zlobintsev/LACT/assets/74719181/6aa87a86-32ac-40e9-bdc3-f1167fb30d61)

Changing clockspeed, voltages and power limit as superuser in one go does not solve it. So likely kernel issue.
```
#! /bin/bash
sudo su <<EOF
echo 402000000 > /sys/class/drm/card1/device/hwmon/hwmon1/power1_cap
echo "s 1 3000" > /sys/class/drm/card1/device/pp_od_clk_voltage
echo "m 1 1250" > /sys/class/drm/card1/device/pp_od_clk_voltage
echo "vo -150" > /sys/class/drm/card1/device/pp_od_clk_voltage
```
