### ISSUE TITLE
Vega 64 - Voltage not applying after PC restart

### ISSUE THREAD

**Issue by Covin90** [ilya-zlobintsev/LACT#339]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Hello,

There's an issue on my machine with changing the voltage value, if I change the voltage and I restart the pc the voltage value is gonna be reverted to the default one 1.2v, the only way to fix this temporarely is to do these steps:

1 - Revert all the values to default
2 - Restart the pc
3 - Apply the new voltage value

In this case the new GPU voltage value is gonna be applied, but the moment I need to restart the pc then the same problem will arise.

![Screenshot from 2024-06-06 22-42-35](https://github.com/ilya-zlobintsev/LACT/assets/58235174/40600419-fd60-4c81-b36b-9da571a76fb5)

[LACT-sysfs-snapshot-20240606-223901.tar.gz](https://github.com/user-attachments/files/15686261/LACT-sysfs-snapshot-20240606-223901.tar.gz)

I've attached a screenshot and the debug snapshot as well,

Thank you

### System info

```markdown
- LACT version: lact-libadwaita 0.5.4-2
- GPU model: AMD Radeon RX Vega 64
- Kernel version: Linux PC-archlinux 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux
- Distribution: Arch Linux
```

**Comment by ilya-zlobintsev** [comment]
After the system boots and the voltage value is not applied, can you try restarting the service (`sudo systemctl restart lactd`) - does it change anything?

I'm also unable to reproduce this on a Vega 56.

**Comment by Covin90** [comment]
I tried to issue the command but it doesn't change the behavior, the voltage is still locked at 1.2v even though I've set 1.1v in the app.

This is a screenshot right after the pc booted,

![Screenshot from 2024-06-07 11-13-43](https://github.com/ilya-zlobintsev/LACT/assets/58235174/6b12627c-d045-432b-8e80-600f753cdf7b)

This one instead after I run and close a game, it seems like the voltage and memory clock value gets locked at the highest power state.

![Screenshot from 2024-06-07 11-18-23](https://github.com/ilya-zlobintsev/LACT/assets/58235174/9ae76827-2bf9-44ed-9893-5434747c7330)

**Comment by ilya-zlobintsev** [comment]
Hmm, it looks like the voltage is actually configured (as you can see in the sliders - those show the value from the GPU, not just what you've configured it to before), but the problem is that the GPU doesn't always use this voltage.

LACT does not control specifically what voltage the GPU runs on, it just sets the voltage values at the appropriate p-states, and then the GPU clocks itself according to those p-states. So I'm afraid this is a GPU firmware issue, and there's not much that can be done on LACT's side.

You can also try changing the performance level or disabling certain power states to see if it changes this behaviour.

**Comment by mbrowars** [comment]
Same problem exist on my vega56. 
![image](https://github.com/ilya-zlobintsev/LACT/assets/74405716/46bfbbd1-881d-46db-8961-94f26bed1c82)

But in addition the voltage isnt changed at all even after i try to reapply the setting.

**Comment by ilya-zlobintsev** [comment]
@mbrowars could you be more specific which version you're currently running, and with which version it worked before?

**Comment by mbrowars** [comment]
@ilya-zlobintsev Im sorry but I wasnt able to find a hint for the last working version. As it turns out it was enough to delete the the /etc/lact/config.yaml and reinstall the tool. Now everything works fine again. I might have messed things up in the config.

**Comment by Covin90** [comment]
> @ilya-zlobintsev Im sorry but I wasnt able to find a hint for the last working version. As it turns out it was enough to delete the the /etc/lact/config.yaml and reinstall the tool. Now everything works fine again. I might have messed things up in the config.

@ilya-zlobintsev The issue is still present on my machine even though I delete this file, checking online I've found this issue is referenced in other places and especially in this link with a proposed fix:

https://bugzilla.kernel.org/show_bug.cgi?id=205277
https://github.com/ROCm/ROC-smi/issues/62

Could this help regarding the problem with the voltage setting?
