### ISSUE TITLE
Control CPU/system fans

### ISSUE THREAD

**Issue by Atemu** [ilya-zlobintsev/LACT#348]
LACT does a great job at controlling GPU related settings. Would it be possible to extend it to CPU and system fans too?

Many motherboards can be controlled in this way using hwmon's pwm sysfs interfaces.

One of the main difficulties with this would be that the fans are usually not labelled correctly, making it impossible which fans are the CPU, which ones the GPU and which ones not connected at all.

**Comment by ilya-zlobintsev** [comment]
This was already previously requested, but no. It is out of scope of the project - I'm intending to keep LACT a tool specifically for GPUs.
There are many other solutions for fan control already: https://wiki.archlinux.org/title/Fan_speed_control

**Comment by Atemu** [comment]
That's understandable.

All the existing tools I could find didn't look to promising.

**Comment by Atemu** [comment]
Would be willing to accept a patch for this? No plans or promises, I'm just considering an eventuality where a wave of motivation to do this hits me.

**Comment by ilya-zlobintsev** [comment]
Right now - probably not. Most configuration is saved/applied per-GPU, so implementing this would require significant overhauls. My stance on this could change at some point, but currently I'd prefer not to have it.
