### ISSUE TITLE
Updated to lact v0.5.5 earlier today and it led to massive instability on Ubuntu 24.04

### ISSUE THREAD

**Issue by Thorazin** [ilya-zlobintsev/LACT#349]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Earlier today I updated to the latest release of l;act via the deb package for ubuntu 24.04 My computer immediately began crashing. I found I could trigger it by visiting a certain website (landroverusa.com) and browsing through the same steps. My first troubleshooting step was to run memtest. That passed with zero errors. I then ran "sudo apt autoremove lact" and rebooted. No more system instability and I can once again browse the website without crashing and my system is stable once more.

### System info

```markdown
- LACT version: v0.5.5
- GPU model:Powercolor RX 7900XTX Red Devil
- Kernel version:6.8.0.39
- Distribution:Ubuntu 24.04
```

**Comment by ilya-zlobintsev** [comment]
Please post the config from `/etc/lact/config.yaml`. The latest release fixed some settings not applying, so it is possible that you have some settings set that cause system instability, and they weren't actually applied previously, but now are.

**Comment by Thorazin** [comment]
Well, I had to delete the v0.5.5 LACT because of the instability it was causing. I guess I can reinstall and get some data if you don't mind waiting until I have finished working today.

Thank you.

**Comment by Thorazin** [comment]
daemon:
  log_level: info
  admin_groups:
  - wheel
  - sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:744C-148C:2422-0000:03:00.0:
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      static_speed: 1.0
      temperature_key: edge
      interval_ms: 500
      curve:
        40: 0.2
        50: 0.35
        60: 0.5
        70: 0.75
        80: 1.0
      spindown_delay_ms: 5000
      change_threshold: 2
    pmfw_options:
      acoustic_limit: 1500
      acoustic_target: 1250
      minimum_pwm: 35
      target_temperature: 94
    power_cap: 402.0
    performance_level: auto
    max_core_clock: 3000
    max_memory_clock: 1500
    voltage_offset: 0
    power_states: {}

**Comment by Thorazin** [comment]
I have a debug snapshot if you want it as well.

**Comment by ilya-zlobintsev** [comment]
There are a lot of settings changed - try removing the config to reset everything, and then applying them individually to see which ones cause the problem.

In particular, the 3000MHz core clock seems very high, that 7900 XTX has the default base clock 2029MHz and boost 2565MHz.

**Comment by Thorazin** [comment]
ok, I cant add screencaps so I zipped them.

[screencaps.zip](https://github.com/user-attachments/files/16437821/screencaps.zip)

**Comment by ilya-zlobintsev** [comment]
Interesting, the rated core clock values for this card are different: https://www.techpowerup.com/gpu-specs/powercolor-red-devil-rx-7900-xtx.b9945
(the VRAM clock is correct though, it's normal for it to be half of the effective value)

Is the instability gone now though?

**Comment by Thorazin** [comment]
So far, so good, I switched the fan from Automatic to Curve as my first change and all is well.

**Comment by Thorazin** [comment]
Upping the power limit to 350W so far has also not led to instability.

**Comment by ilya-zlobintsev** [comment]
Then it looks like the problem was indeed caused by unstable clockspeed settings.
