### ISSUE TITLE
Power usage limit

### ISSUE THREAD

**Issue by blacky-hh** [ilya-zlobintsev/LACT#354]
Hey,

if i edit the config.yaml "power_cap" to 315, it will reset to default.
is it prosible to make a custum value at the gui?

my 6900xt only reaches 293W at max power limit. stock ist set to 253W!?

greetings

**Comment by ilya-zlobintsev** [comment]
You can't set the limit above the value allowed by the hardware, the driver won't apply it.

**Comment by blacky-hh** [comment]
Hmm... thats mad. Under Windows thats possible..."MorePowerTool".

**Comment by ilya-zlobintsev** [comment]
MorePowerTool works by directly editing gpu power tables, rather than operating within the normally provided limits. LACT should allow you to change it the same as amd's control panel on windows (at least for RDNA2).
