### ISSUE TITLE
Fan curve editing crashes when any non-numerical string is entered

### ISSUE THREAD

**Issue by ahydronous** [ilya-zlobintsev/LACT#355]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Edit one of the points on the fan curve and enter anything non-numerical. For example `55C`. Press enter.
LACT will immediately crash.
Entering a non-integer value like `55.1` also acts a bit strange. Although these should just be rounded to the nearest value.

### System info

```markdown
- LACT version: 0.5.4
- GPU model: ASrock Taichi 6800XT
- Kernel version 6.10.3
- Distribution: NixOS 24.05
```

**Comment by ilya-zlobintsev** [comment]
Fixed in https://github.com/ilya-zlobintsev/LACT/commit/fe0f8b5e5264c699115418cc0d293d74e30e6ace
