### ISSUE TITLE
My card model (Asrock Taichi 6800XT) isn't recognized properly, detected as "Unknown (0x5201)"

### ISSUE THREAD

**Issue by ahydronous** [ilya-zlobintsev/LACT#356]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Not much to say but what's in the title.
![image](https://github.com/user-attachments/assets/966e9245-2c0a-433f-bae8-ac2a421c4efb)

### System info

```markdown
- LACT version:0.5.4
- GPU model: ASrock Taichi 6800XT
- Kernel version: 6.10.3
- Distribution: NixOS 24.05
- Driver: radv, Mesa 24.0.7
```

**Comment by ahydronous** [comment]
[LACT-sysfs-snapshot-20240814-125805.tar.gz](https://github.com/user-attachments/files/16611908/LACT-sysfs-snapshot-20240814-125805.tar.gz)

**Comment by ilya-zlobintsev** [comment]
This just means that this Asrock model is not in the system's PCI device database. This happens often as not every card variation is there. LACT itself doesn't ship model info.

You can try submitting it to the PCI ID database: https://pci-ids.ucw.cz/
