### ISSUE TITLE
Save debug snapshots to `XDG_DATA_HOME/Downloads/` instead of `/tmp`

### ISSUE THREAD

**Issue by ahydronous** [ilya-zlobintsev/LACT#357]
Saving debug snapshots to `/tmp/` is both less discoverable and annoying to remove the snapshot due to root access requirements.

**Comment by ilya-zlobintsev** [comment]
The reason it's in `/tmp` is that you don't need to remove it manually, it will get cleaned up when you reboot the system. Is there a reason why you want to do it manually?

Discoverability should be fine too since the GUI shows a popup window with the path where it was stored.

**Comment by ahydronous** [comment]
Ah, mine doesn’t clean out that file on reboot. Perhaps a quirk of NixOS.

**Comment by ilya-zlobintsev** [comment]
Apparently you have to explicitly set the `boot.cleanTmpDir = true; ` option on NixOS.

I'm not going to change this as putting the snapshots in downloads would mean that you do actually have to manually clean them up.
