### ISSUE TITLE
Make an option to put a LACT indicator in the menu bar, to make visible that the daemon is still running in the background

### ISSUE THREAD

**Issue by ahydronous** [ilya-zlobintsev/LACT#358]
I understand that technically this is not needed, but it is nice to have explicit confirmation.

**Comment by ilya-zlobintsev** [comment]
This isn't really possible as is, since the daemon runs as root without being bound to a graphical session. It would need to be a separate process just for the tray icon, which I think would be overkill (and this process could exit without the actual daemon exiting).

**Comment by ahydronous** [comment]
Ah, good point. Thanks for the consideration!
