### ISSUE TITLE
Introduce some sort of crash watchdog that resets GPU (especially the fan curve) to default on lactD crash.

### ISSUE THREAD

**Issue by ahydronous** [ilya-zlobintsev/LACT#359]
I use another fan control solution on Windows (Fan Control, although that developer ignored my concerns , https://github.com/Rem0o/FanControl.ADLX/issues/47).
The ALDX wrapper for that is/was crash prone, and it crashes silently. This nearly fried my GPU due to my fan being stuck at a low set percentage during gaming which caused the card to eventually go into emergency thermal shutdown.

It would be good if there was some sort of guard against this.

**Comment by ilya-zlobintsev** [comment]
Done in https://github.com/ilya-zlobintsev/LACT/commit/48c4a8a102b15ef6b0eed9027212c7b9384f09c7 (systemd will restart the service in case it fails).
