### ISSUE TITLE
Error while compiling from source

### ISSUE THREAD

**Issue by Who-are-me** [ilya-zlobintsev/LACT#365]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

I try compiling from source, and i have error ->

 Compiling lact-daemon v0.5.5 (/home/forever/Templates/LACT/lact-daemon)
   Compiling lact-gui v0.5.5 (/home/forever/Templates/LACT/lact-gui)
error: proc macro panicked
   --> lact-gui/src/app/graphs_window/mod.rs:144:14
    |
144 |     #[derive(CompositeTemplate, Default)]
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: message: blueprint-compiler not found
    = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
  --> lact-gui/src/app/info_row.rs:32:14
   |
32 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: blueprint-compiler not found
   = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
  --> lact-gui/src/app/page_section.rs:37:14
   |
37 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: blueprint-compiler not found
   = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
   --> lact-gui/src/app/root_stack/info_page/hardware_info.rs:147:14
    |
147 |     #[derive(CompositeTemplate, Default, Properties)]
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: message: blueprint-compiler not found
    = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
  --> lact-gui/src/app/root_stack/info_page/vulkan_info/feature_window/row.rs:31:14
   |
31 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: blueprint-compiler not found
   = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
  --> lact-gui/src/app/root_stack/info_page/vulkan_info/feature_window/mod.rs:38:14
   |
38 |     #[derive(CompositeTemplate, Properties, Default)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: blueprint-compiler not found
   = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
   --> lact-gui/src/app/root_stack/oc_page/gpu_stats_section.rs:104:14
    |
104 |     #[derive(CompositeTemplate, Default, Properties)]
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: message: blueprint-compiler not found
    = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
  --> lact-gui/src/app/root_stack/oc_page/power_cap_section.rs:44:14
   |
44 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: blueprint-compiler not found
   = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
   --> lact-gui/src/app/root_stack/oc_page/power_profile/power_profile_heuristics_grid.rs:126:14
    |
126 |     #[derive(CompositeTemplate, Default)]
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: message: blueprint-compiler not found
    = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
  --> lact-gui/src/app/root_stack/oc_page/power_states/power_state_row.rs:37:14
   |
37 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: blueprint-compiler not found
   = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
  --> lact-gui/src/app/root_stack/oc_page/power_states/power_states_frame.rs:81:14
   |
81 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: blueprint-compiler not found
   = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
   --> lact-gui/src/app/root_stack/oc_page/power_states/power_states_list.rs:103:14
    |
103 |     #[derive(CompositeTemplate, Default, Properties)]
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: message: blueprint-compiler not found
    = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc macro panicked
  --> lact-gui/src/app/root_stack/software_page.rs:52:14
   |
52 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: blueprint-compiler not found
   = note: this error originates in the derive macro `CompositeTemplate` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `lact-gui` (lib) due to 13 previous errors
warning: build failed, waiting for other jobs to finish...

### System info

```markdown
- LACT version: 0.5.5
- GPU model: vega 56
- Kernel version: 6.10.5-10-default
- Distribution: OpenSUSE Tumbleweed
```

**Comment by ilya-zlobintsev** [comment]
>  = help: message: blueprint-compiler not found

You need to install `blueprint-compiler`, it's a build-time dependency.
