### ISSUE TITLE
Update readme about nixos

### ISSUE THREAD

**Issue by furdiburd** [ilya-zlobintsev/LACT#374]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

The LACT package is now in stable channel of nixos, the readme should be update to reflect this and link to the stable channel version

(https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=lact)

### System info

```markdown
-
```

**Comment by ilya-zlobintsev** [comment]
https://github.com/ilya-zlobintsev/LACT/commit/30df3ee11bcc3d3d922ff1bbf72a1044300e97fe
