### ISSUE TITLE
Unable to change over drive (boost) clock.

### ISSUE THREAD

**Issue by czar** [ilya-zlobintsev/LACT#376]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

I would like to be able to change the Boost clock, as it's causing some crashes.  I'm not finding a way to-do this.  I assume this is a bug with lact and or my drivers?  TYVM

per techpowerup the RX 7900GRE  Boost Clock should be  2245-2366 MHz but here is what pp_od_clk_voltage  says, (2803Mhz) and VRAM should be 1125.    

//over drive (boost) clock and voltage configuration
cat /sys/class/drm/card1/device/pp_od_clk_voltage 
OD_SCLK:
0: 500Mhz
1: 2395Mhz
OD_MCLK:
0: 97Mhz
1: 1125MHz
OD_VDDGFX_OFFSET:
0mV
OD_RANGE:
SCLK:     500Mhz       2803Mhz
MCLK:      97Mhz       1158Mhz
VDDGFX_OFFSET:    -350mv          0mv

![image](https://github.com/user-attachments/assets/f45690b8-95cd-4e85-ab3a-64f763eaab2f)

### System info

```markdown
- LACT version: 0.5.6-0
- GPU model:  AMD Radeon rx 7900 gre  (XFX brand)
- Kernel version: Linux lab0 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Distribution:  Ubuntu 22.04.4 LTS
```

[LACT-sysfs-snapshot-20240914-111328.tar.gz](https://github.com/user-attachments/files/17002938/LACT-sysfs-snapshot-20240914-111328.tar.gz)

**Comment by ilya-zlobintsev** [comment]
> per techpowerup the RX 7900GRE Boost Clock should be 2245-2366 MHz

And, as listed in your screenshot, the max GPU clock is 2395MHz, which nearly lines up with the specs. The 2803MHz value is in the `OD_RANGE` section of the file. It's the highest possible value that you can possibly set, not the current one.

You can change the maximum clockspeed in LACT. Is the setting not working?

**Comment by ilya-zlobintsev** [comment]
Regarding crashes: you should try updating to a newer version of ubuntu, there have been bug fixes in newer versions of GPU firmware and mesa.
