### ISSUE TITLE
Cannot build on EL8

### ISSUE THREAD

**Issue by xander-st-aubyn** [ilya-zlobintsev/LACT#377]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Glib-2.56 (the version installed on EL8) is too old for the version of the rust crate glib-sys requires which is 2.68 I believe or 67.

Since Enterprise Linux 8 is supported until nearly the end of the decade it would be great if one could use lact on it.

### System info

```markdown
- LACT version: Any
- GPU model: AMD Radeon RX 6650 XT - AMD/ATI Navi 23
- Kernel version: 4.18 (Though I am planning to compile a newer perhaps 5x or 6x)
- Distribution: Enterprise Linux 8.10 (any RHEL 8x)
```

**Comment by ilya-zlobintsev** [comment]
RHEL 8 doesn't ship GTK4. LACT requires GTK4 (short of using only the daemon without GUI). Maybe you could build GTK/glib from source, but it's likely not a simple process.

You might however be able to run LACT inside of a newer distro's environment using something like [distrobox](https://github.com/89luca89/distrobox/tree/main), provided the container has [root access](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#run-the-container-with-real-root) to `/sys`.

**Comment by ilya-zlobintsev** [comment]
> I would be fine with a small service and all it does is take a fan curve from a config file and override that zero-speed fan control so they run according to the curve

It should be possible to do this with LACT already - you can build with `make build-release-headless` and it will not depend on GTK at all. Also see the [api description](https://github.com/ilya-zlobintsev/LACT/blob/master/API.md).

**Comment by ilya-zlobintsev** [comment]
Yes, that is correct. The changes should even be detected automatically when you edit the config file.

**Comment by ilya-zlobintsev** [comment]
The daemon is already separated - you've just built it separately, and there are headless builds provided in releases. However the CLI is indeed very limited. I think maybe it would be better to document the configuration file and make it easier to manually edit rather than adding everything via cli commands though.

**Comment by ilya-zlobintsev** [comment]
https://github.com/ilya-zlobintsev/LACT/pull/379 should give more options with your setup: now you can run the daemon on your primary system, and connect to it remotely from another environment that's new enough for the GUI (container or otherwise).

**Comment by ilya-zlobintsev** [comment]
There are prebuilt packages for RHEL now as well.
