### ISSUE TITLE
AMD GPU Fan speed control

### ISSUE THREAD

**Issue by alisson3000br** [ilya-zlobintsev/LACT#378]
So i'm trying many ways to solve this noisy issue, in this ubuntu the fan is always full speed. its a gigabyte a320m-h, AMD RX550, but nothing gets the fan to show up in watch sensors it is N/A for fan, so i guess this gpu is not in the kernel or the OS i dont know, it does not identifies, does somebody know why, or what explains this, because in windows the speed change works and it is quiet

**Comment by ilya-zlobintsev** [comment]
Please include a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues)

**Comment by alisson3000br** [comment]
[LACT-sysfs-snapshot-20240919-090200.tar.gz](https://github.com/user-attachments/files/17058692/LACT-sysfs-snapshot-20240919-090200.tar.gz)

**Comment by ilya-zlobintsev** [comment]
Are you sure the fan control doesn't work? The GPU doesn't seem to report its RPM (this is why `sensors` doesn't show the speed), but it exposes the controls for it. You've set the speed 10%, it it not getting applied?

**Comment by alisson3000br** [comment]
sure it does not work, well it is the gpu fan and the maker (brand) of the gpu that made it like this, i just replaced the fan with a custom fan and it is even cooler

**Comment by alisson3000br** [comment]
cooler and quiet, actually in windows was the same thing, i was mistaken

**Comment by alisson3000br** [comment]
anyways thanks !!!!!!! i will close then the issue
