### ISSUE TITLE
GUI fails to start

### ISSUE THREAD

**Issue by 43615** [ilya-zlobintsev/LACT#381]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

The GUI fails to start after some updates. `lactd.service` appears to run fine.
```
$ lact

(lact:4810): Gtk-WARNING **: 08:13:18.220: Unknown key gtk-modules in /home/aegis/.config/gtk-4.0/settings.ini
2024-09-23T06:13:18.279445Z  INFO lact_client::connection::unix: connecting to service at "/var/run/lactd.sock"
Gdk-Message: 08:13:18.279: Error 71 (Protocol error) dispatching to Wayland display.
```

### System info

```markdown
- LACT version: 0.5.6
- GPU model: AMD Navi 31
- Kernel version: 6.10.10-arch1
- Distribution: Arch Linux x64
- DE: KDE Plasma on Wayland
```

**Comment by ilya-zlobintsev** [comment]
Do other GTK4 applications work? Like `gtk4-demo` from the `gtk4-demos` package

**Comment by 43615** [comment]
Same error, seems to be a larger GTK issue. Thanks for the tip!
