### ISSUE TITLE
Failed to start daemon NixOS

### ISSUE THREAD

**Issue by levitskyyy** [ilya-zlobintsev/LACT#382]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Systemctl enable:
```
sudo systemctl enable lactd
Failed to enable unit: Unit file lactd.service does not exist.

sudo systemctl start lact-daemon
Failed to start lact-daemon.service: Unit lact-daemon.service not found.
```

### while the lact daemon command works successfully:
```
lact daemon
2024-09-24T00:21:36.594713Z  INFO lact_daemon::socket: listening on "/var/run/user/1000/lactd.sock"
2024-09-24T00:21:36.611865Z  INFO lact_daemon::server::handler: initialized 1 GPUs
```

### System info

```markdown
- LACT version: latest
- Kernel version: 6.6.52
- Distribution: NixOS
```

**Comment by ilya-zlobintsev** [comment]
Seems to be an issue with the nix package, apparently you have to do this for the service to appear:
https://wiki.nixos.org/wiki/AMD_GPU#GUI_tools

I don't maintain the nix package nor use nixos so I can't confirm this for sure though.
