### ISSUE TITLE
failed to compile lact

### ISSUE THREAD

**Issue by VaporeonScripts** [ilya-zlobintsev/LACT#386]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

![image](https://github.com/user-attachments/assets/6a706d08-b788-4996-815e-d32bd9415645)

### System info

```markdown
- LACT version: latest commit (or atleast, i was trying to update to that)
- GPU model: 6750xt 
- Kernel version: latest 6.11.3-1
- Distribution: CachyOS (Arch Based)
```

**Comment by ilya-zlobintsev** [comment]
Fixed in https://github.com/ilya-zlobintsev/LACT/commit/96bebf4ee4d66fb7687a70ea054fdcb46c8cd03a
