### ISSUE TITLE
Master does not build on Debian Testing (yeslogic-fontconfig-sys)

### ISSUE THREAD

**Issue by knuxyl** [ilya-zlobintsev/LACT#395]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Library yeslogic-fontconfig-sys is calling unwrap() on an Err value and my compiler doesn't like that. I'm guessing something in the dependency tree didn't check this library before updating the version in the toml, or are just using *.
I'm on a gnome session and using this command
`make build-release-libadwaita`

> error: failed to run custom build command for `yeslogic-fontconfig-sys v5.0.0`
> 
> Caused by:
>   process didn't exit successfully: `/home/knuxyl/Mount/4tb1/system/source/LACT/./target/release/build/yeslogic-fontconfig-sys-3f311538a387ffb2/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-env-changed=RUST_FONTCONFIG_DLOPEN
>   cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=FONTCONFIG_STATIC
>   cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
> 
>   --- stderr
>   thread 'main' panicked at /home/knuxyl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yeslogic-fontconfig-sys-5.0.0/build.rs:8:48:
>   called `Result::unwrap()` on an `Err` value: "\npkg-config exited with status code 1\n> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags fontconfig\n\nThe system library `fontconfig` required by crate `yeslogic-fontconfig-sys` was not found.\nThe file `fontconfig.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.\nThe PKG_CONFIG_PATH environment variable is not set.\n\nHINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `fontconfig.pc`.\n"
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> make: *** [Makefile:9: build-release-libadwaita] Error 101

### System info

```markdown
- LACT version: Master
- GPU model: Pro W6600
- Kernel version: 6.11.4
- Distribution: Debian Testing (currently Trixie)
- Cargo/Rustc: 1.81.0
```

**Comment by ilya-zlobintsev** [comment]
This is due to a missing build dependency: `The system library fontconfig required by crate yeslogic-fontconfig-sys`

I've just tested building in a docker container, and this is the list of dependencies needed to build on debian testing:
```
apt install make cargo libgtk-4-dev blueprint-compiler libdrm-dev libadwaita-1-dev
```

**Comment by knuxyl** [comment]
i already had fontconfig and libfontconfig-dev installed. i mustve skipped over some of the packages, this fixed it. thank you
