### ISSUE TITLE
Fedora 41 Release

### ISSUE THREAD

**Issue by porkloin** [ilya-zlobintsev/LACT#396]
Fedora 41 is out now, is it possible to get an F41 tagged release?

**Comment by ilya-zlobintsev** [comment]
I'll add it, but you can just use the older rpm for now as it will work fine in 99% of cases

**Comment by porkloin** [comment]
Yeah sorry I forgot to add that when I opened the issue, but I was able to install the F40 rpm totally fine, works great on my ublue-based machine with `rpm-ostree install {lact-f40path}`

**Comment by ilya-zlobintsev** [comment]
`dnf/rpm-ostree install lact` won't work regardless since the package isn't published in any repo, you always have to install it from a local file.

**Comment by KyleGospo** [comment]
> `dnf/rpm-ostree install lact` won't work regardless since the package isn't published in any repo, you always have to install it from a local file.

Any interest in getting this into a copr repo? Would be huge for this purpose, and prevent the need to do updates like this since copr can fork for Fedora releases.

**Comment by ilya-zlobintsev** [comment]
> Any interest in getting this into a copr repo?

If someone is willing to maintain it, then this would be great. It would be ideal if we could get LACT into Fedora repositories proper or into RPM fusion, but I'm not sure what the process for that is.
