### ISSUE TITLE
works with w7900 dual slot?

### ISSUE THREAD

**Issue by johnnynunez** [ilya-zlobintsev/LACT#397]

**Comment by johnnynunez** [comment]
Well it is working, but fan and voltage not
![image](https://github.com/user-attachments/assets/bf8f7d13-5694-4836-b70c-3e0cd9f0a0c7)
![image](https://github.com/user-attachments/assets/b24bd86a-b963-4368-a29f-93cd5b86ca69)

**Comment by ilya-zlobintsev** [comment]
On your second screenshot there is a message saying what's wrong.
