### ISSUE TITLE
Core/Mem Freq not restored after suspend or written to Json by GUI

### ISSUE THREAD

**Issue by Big-FG** [ilya-zlobintsev/LACT#41]
Ive noticed that on my 5700xt the values for core/mem freq arent restored by the daemon upon returning from system suspend state. The power limit and fan curves work as desired but not the clocks.

The core/mem freq also arent written to the json file by the gui  which im not sure if thats intentional. If you manually edit the json its fine.

**Comment by Big-FG** [comment]
I was looking at other amdgpu related tools and noticed in amdgpu-clocks there is a section about restarting upon resume after suspend. not sure if this helps

https://github.com/sibradzic/amdgpu-clocks

**Comment by Big-FG** [comment]
Ill create a service and see if this works for resume on suspend

**Comment by Big-FG** [comment]
I created a lactd-resume.service and enabled it
this seems to resolve the reapplying on resume from suspend and it also includes hibernate and sleep targets. Needs more testing but it restarts lactd upon resume

`[Unit]
Description=AMDGPU Control Daemon Resume
After=hibernate.target
After=hybrid-sleep.target
After=suspend.target
After=suspend-then-hibernate.target

[Service]
ExecStart=/bin/systemctl --no-block restart lactd.service

[Install]
WantedBy=graphical.target
WantedBy=hibernate.target
WantedBy=hybrid-sleep.target
WantedBy=suspend.target
WantedBy=suspend-then-hibernate.target`

**Comment by ilyazzz** [comment]
Hmm, this seems like a bit of a hack to call `systemctl restart` from another systemd unit, but I'll look into it.

**Comment by ilya-zlobintsev** [comment]
This is now fixed, LACT will reapply all settings on suspend/resume events received from dbus.
