### ISSUE TITLE
v0.6.0 changelog goes here

### ISSUE THREAD

**Issue by Atemu** [ilya-zlobintsev/LACT#411]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

v0.6.0 changelog goes here

;)

### System info

```markdown
- LACT version:
- GPU model:
- Kernel version:
- Distribution:
```

**Comment by ilya-zlobintsev** [comment]
The github release is created automatically now, but I still generate and edit the changelog manually, so there's a brief window where the changelog isn't there yet. It might be a good idea to mark the release as draft until I fill it out.

Regardless, it's filled now :D

**Comment by Atemu** [comment]
Haha okay, thanks :)
