### ISSUE TITLE
[Error] Segmentation Fault (SIGSEGV) During Compilation of lact-git on Arch Linux with yay

### ISSUE THREAD

**Issue by brockar** [ilya-zlobintsev/LACT#413]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

When attempting to compile the `lact-git` package on Arch Linux using `yay`, the process fails due to a segmentation fault. The error indicates an "invalid memory reference (signal: 11, SIGSEGV)" during the build of the `darling_core` library. 

**Environment**:
- **OS**: Arch Linux
- **Installation Tool**: `yay`
- **Rust Version**: `rustc 1.82.0 (f6e511eec 2024-10-15)`
- **Steps Taken**: Tried clearing cache, updating dependencies, and increasing swap space, but the issue persists.

**Steps to Reproduce**:
1. Run `yay -S lact-git` on an updated Arch Linux system.
2. Observe the segmentation fault error during compilation.

The build fails with a segmentation fault error (`SIGSEGV`), specifically when compiling the `darling_core` library.

**Error Log**:  
[Log](https://pastebin.com/7QgXmDcg)

### System info

```markdown
- LACT version: -
- GPU model: NVIDIA 3070 LHR
- Kernel version: 6.11.7-zen1-1-zen
- Distribution: Arch Linux
- VM: Hyprland (Wayland)
- Ram: 3.87 GiB / 31.27 GiB
```

**Comment by brockar** [comment]
Yes, it happened with both.
I tried using `rustup default 1.81` and setting `CARGO_BUILD_JOBS=1`, and now it works for lact-git.
I'm not sure which one resolved the issue, but it works now. Thanks for the help! :)

**Comment by brockar** [comment]
Now the program installed with these warnings:
```bash
warning: Unused import: Pango  
at <stdin> line 3 column 1:  
   3 |using Pango 1.0;  
     |^^^^^^^^^^^^^^^^  
suggestion: remove using Pango 1.0;  

warning: Unused import: Gtk  
at <stdin> line 2 column 1:  
   2 |using Gtk 4.0;  
     |^^^^^^^^^^^^^^  
suggestion: remove using Gtk 4.0;  
```
And when I try to run it, I get the following errors, and it fails to start:
[pastebin](https://pastebin.com/KshUL6iJ)

**Comment by ilya-zlobintsev** [comment]
Does it work when [enabling the service](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#usage)? It should have a running service status (`systemctl status lactd`) and the GUI should be able to connect to it.

You also seem to have a broken GTK theme configuration, but this isn't critical and doesn't prevent lact from starting.

**Comment by brockar** [comment]
Now it works, it was my mistake, sorry.
Just setting `CARGO_BUILD_JOBS=1` during installation makes it work.

Thank you for the responses.
