### ISSUE TITLE
maybe add note to readme about finer fan control

### ISSUE THREAD

**Issue by Big-FG** [ilya-zlobintsev/LACT#42]
I noticed in the readme that nothing about doing finer control of the fan curve is mentioned. The daemon seems to have no problem with doing this if you manually create fan speed and temp targets in the Json and works well for creating specific temp/fan targets. I havent tested beyond adding just one step fyi but fan control seems to work much better than radeon-profile and corectrl which both seem to cause the fan to get stuck in higher speed modes

I.E

default
```
"fan_control_enabled": true,
        "fan_curve": {
          "20": 0.0,
          "40": 0.0,
          "60": 50.0,
          "80": 75.0,
          "100": 100.0
```

edited to add 0rpm fan mode below 50c

```
"fan_control_enabled": true,
        "fan_curve": {
          "20": 0.0,
          "40": 0.0,
          "50": 0.0,
          "60": 50.0,
          "80": 75.0,
          "100": 100.0
```

**Comment by ilyazzz** [comment]
While the daemon handles more curve points fine, the GUI is currently hardcoded to only 5 temperature levels and I'm not sure if this config gets displayed properly. I'll look into it.

**Comment by Big-FG** [comment]
No it doesnt get displayed in the GUI but the CLI shows it

**Comment by ilya-zlobintsev** [comment]
The latest version now fully supports editing the curve from GUI.
