### ISSUE TITLE
[Feature Request] Finding that pesky Nvidia vram temp

### ISSUE THREAD

**Issue by doggeddalle** [ilya-zlobintsev/LACT#420]
Is there any chance at all in the future something like this can be implemented to get access to the vram temp
The project in question is here: [link](https://github.com/olealgoritme/gddr6)

This method allows for viewing the vram temp live in terminal but I've tried on and off the past 3 months to formulate a more efficient way of viewing the information by grabbing it from the output. Sadly with no luck. 

however it does rely on direct root access (which could be alleviated on a per user basis) and also iomem relaxed for grub which as stated on their git isn't always needed

The outputs in this application look like this in terminal:
```
Device: RTX 3090 GDDR6X (GA102 / 0x2204) pci=1:0:0
VRAM Temps: |  54°C |
```

Would love to read your thoughts

**Comment by AbdulrahmanObaido** [comment]
can we get intel arc support fan speed set on kernel 6.12 ?
