### ISSUE TITLE
Max GPU Clock value resetting in GUI after applying on Nvidia

### ISSUE THREAD

**Issue by Zennwah** [ilya-zlobintsev/LACT#422]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

The value resets in GUI when I change and apply it. The default value set by LACT for my GPU is 1961 and resets back to it every time. However, the cat output of /etc/lact/config.yaml says e.g. "max_core_clock: 2101" so LACT sets it correctly. Only the GUI value doesn't seem to be persistent after applying and GPU Core Clock (Target) says "N/A". Voltage also doesn't seem to be read by LACT, it always stays at 0.
Other options apply correctly and are persistent.
![image](https://github.com/user-attachments/assets/9fa76b0b-4f26-45da-9ccc-162d6e8d130d)
[LACT-sysfs-snapshot-20241123-204646.tar.gz](https://github.com/user-attachments/files/17882418/LACT-sysfs-snapshot-20241123-204646.tar.gz)

### System info

```markdown
- LACT version: 0.6.0-release (commit 3fd7e0e) but does the same thing on the lact-git AUR package
- GPU model: Gigabyte GTX 1060 6GB Windforce OC
- Kernel version: 6.12.1-2-cachyos
- Distribution: Arch Linux with the CachyOS kernel and GPU drivers installed
- Wayland
```

**Comment by ilya-zlobintsev** [comment]
Looking at the debug snapshot, it looks like the value isn't just not shown in the UI - the nvidia driver reports a clock offset of `0`, despite a custom max clock being set in the config. Interestingly, the memory offset is reported correctly.

Could you check if the GPU actually reaches this clockspeed (or it's at least different from the default one) under load, meaning this is just a reporting issue, or if the value is actually not applied and ignored?

>  GPU Core Clock (Target) says "N/A". Voltage also doesn't seem to be read by LACT, it always stays at 0.

This is normal, those values are only reported on AMD currently.

**Comment by Zennwah** [comment]
MangoHud reports 2100-2075 MHz under load, LACT's GUI does too.
![image](https://github.com/user-attachments/assets/fd6bb2f9-af5c-4385-b7e5-934e0511d0b2)
![image](https://github.com/user-attachments/assets/f4f2a3b0-8e35-4768-b1ee-96ef992b00d3)
![image](https://github.com/user-attachments/assets/6510b729-c938-45be-a114-f9614c677f0f)

**Comment by ilya-zlobintsev** [comment]
Should be resolved with https://github.com/ilya-zlobintsev/LACT/commit/73adb1aba207c7d73102c83329279b1f5bd1fdb3, please try `lact-git`

**Comment by Zennwah** [comment]
Working as expected now. Closing the issue.
