### ISSUE TITLE
How  to enable fan control.

### ISSUE THREAD

**Issue by Jimmytalksalot** [ilya-zlobintsev/LACT#435]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

I want to enable fan control, but it seems I need to add parameters to the config.yaml. When I enable fan control through there, it says that fan control has no settings. So, what do you I add to config.yaml as the settings for fan control? 

![20241229_19h48m39s_grim](https://github.com/user-attachments/assets/27f1d4c6-832d-454a-9c5f-20693fab037f)
  

### System info

```markdown
- LACT version: Git latest
- GPU model: 1650 Mobile Geforce GTX
- Kernel version: Zen latest
- Distribution: Arch Linux
```

**Comment by ilya-zlobintsev** [comment]
The config is not really documented currently since most people change it through the GUI, but here's an example of a custom fan curve:
```
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      temperature_key: edge
      interval_ms: 500
      curve:
        40: 0.2
        50: 0.35
        60: 0.5
        70: 0.75
        80: 1.0
      spindown_delay_ms: 5000
      change_threshold: 2
```

**Comment by ilya-zlobintsev** [comment]
The config is now documented [here](https://github.com/ilya-zlobintsev/LACT/blob/master/docs/CONFIG.md).
